"""Generate src/papers.js from a DBE past-paper index.

The index comes from https://github.com/Willemjvr/sa-matric-papers (index.json),
which scrapes the official Department of Basic Education listings.

    python tools/make_papers.py /path/to/index.json

Only Mathematics and Physical Sciences are kept, English question papers plus
the bilingual memos and the Maths Paper 2 answer book / addendum.
"""

import json
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "src" / "papers.js"

LISTING = "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx"
# Year pages confirmed by search; everything else falls back to the main listing.
SESSION_PAGES = {
    "2017-nov": "https://www.education.gov.za/Home/2017NSCNovemberpastpapers.aspx",
    "2023-nov": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/2023NSCNovemberpastpapers.aspx",
    "2024-nov": "https://www.education.gov.za/2024NSCNovemberpastpapers.aspx",
}
SESSION_NAMES = {"nov": "November", "may_june": "May/June", "feb_march": "Feb/March"}
SESSION_SLUG = {"nov": "nov", "may_june": "jun", "feb_march": "mar"}

# Nov 2017 is missing from the index. The DBE year page lists all four papers;
# the Physics P1 question paper link was confirmed separately.
EXTRA = {
    "2017-nov": {
        "phys": {
            "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=GDvpKcfxROs%3D&tabid=1856&portalid=0&mid=7354",
        },
        "maths": {},
    }
}


def slot(title: str) -> str | None:
    t = title.lower()
    if t.startswith("paper 1 (english)"):
        return "p1"
    if t.startswith("paper 2 (english)"):
        return "p2"
    if t.startswith("memo 1"):
        return "m1"
    if t.startswith("memo 2"):
        return "m2"
    if t.startswith("paper 2 answerbook") or t.startswith("paper 2 addendum"):
        return "ab"
    return None


def main(index_path: str) -> None:
    data = json.loads(Path(index_path).read_text())
    rows = [
        r
        for r in data["papers"]
        if r["subject"] in ("Mathematics", "Physical Sciences") and r["year"] >= 2017
    ]
    # A link shared by two different papers is a scraper mix-up: drop both
    # and let the app send the learner to the official listing instead.
    dup = {u for u, n in Counter(r["url"] for r in rows).items() if n > 1}

    sessions: dict[str, dict] = {}
    for r in rows:
        key = f"{r['year']}-{SESSION_SLUG[r['session']]}"
        s = sessions.setdefault(
            key,
            {
                "key": key,
                "year": r["year"],
                "session": SESSION_SLUG[r["session"]],
                "label": f"{SESSION_NAMES[r['session']]} {r['year']}",
                "page": SESSION_PAGES.get(key, LISTING),
                "maths": {},
                "phys": {},
            },
        )
        subj = "maths" if r["subject"] == "Mathematics" else "phys"
        k = slot(r["title"])
        if k and r["url"] not in dup:
            s[subj][k] = r["url"]

    sessions["2017-nov"] = {
        "key": "2017-nov",
        "year": 2017,
        "session": "nov",
        "label": "November 2017",
        "page": SESSION_PAGES["2017-nov"],
        **EXTRA["2017-nov"],
    }

    order = {"nov": 0, "jun": 1, "mar": 2}
    out = sorted(sessions.values(), key=lambda s: (-s["year"], order[s["session"]]))
    body = json.dumps(out, indent=1, ensure_ascii=False)
    OUT.write_text(
        "// Generated by tools/make_papers.py from the DBE past-paper index. Do not edit by hand.\n"
        f"const PAPERS_SOURCE = {json.dumps(data.get('scraped_at', ''))};\n"
        f"const DBE_LISTING = {json.dumps(LISTING)};\n"
        f"const PAPERS = {body};\n"
    )
    print(f"wrote {OUT} with {len(out)} sessions; dropped {len(dup)} duplicate link(s)")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "index.json")
