// Flashcard decks. The two definition decks are built from the topic data so
// they always match what the topic pages say.

const defsFrom = (paper) =>
  PHYS_TOPICS.filter((t) => t.paper === paper && t.defs).flatMap((t) =>
    t.defs.map(([term, def]) => ({ f: term, b: def, topic: t.id }))
  );

const DECKS = [
  {
    id: "phys-defs",
    subj: "phys",
    name: "Physics definitions",
    blurb: "Paper 1. Definitions are 2–3 marks each and are marked word for word.",
    cards: defsFrom(1),
  },
  {
    id: "chem-defs",
    subj: "phys",
    name: "Chemistry definitions",
    blurb: "Paper 2. Learn the key words in each one: the memo looks for them.",
    cards: defsFrom(2),
  },
  {
    id: "organic",
    subj: "phys",
    name: "Organic families & reactions",
    blurb: "Suffixes, functional groups and reaction conditions.",
    cards: [
      { f: "Suffix -ane", b: "Alkane. Only single C–C bonds. CₙH₂ₙ₊₂" },
      { f: "Suffix -ene", b: "Alkene. A C=C double bond. CₙH₂ₙ" },
      { f: "Suffix -yne", b: "Alkyne. A C≡C triple bond. CₙH₂ₙ₋₂" },
      { f: "Suffix -ol", b: "Alcohol. Functional group –OH (hydroxyl)" },
      { f: "Suffix -al", b: "Aldehyde. Functional group –CHO (formyl), always on carbon 1" },
      { f: "Suffix -one", b: "Ketone. C=O inside the chain (carbonyl)" },
      { f: "Suffix -oic acid", b: "Carboxylic acid. Functional group –COOH (carboxyl)" },
      { f: "Name ending -yl -oate", b: "Ester, e.g. ethyl propanoate. Alcohol part first, acid part second" },
      { f: "Prefixes for 1 to 8 carbons", b: "meth, eth, prop, but, pent, hex, hept, oct" },
      { f: "Alkene + H₂O →", b: "Alcohol. Addition (hydration). Catalyst H₃PO₄ or H₂SO₄" },
      { f: "Alkene + H₂ →", b: "Alkane. Addition (hydrogenation). Catalyst Pt, Pd or Ni" },
      { f: "Alkene + HBr →", b: "Haloalkane. Addition (hydrohalogenation). Major product: H goes to the C with more H atoms" },
      { f: "Haloalkane + concentrated NaOH in ethanol, strong heat →", b: "Alkene. Elimination (dehydrohalogenation)" },
      { f: "Haloalkane + dilute NaOH(aq), mild heat →", b: "Alcohol. Substitution (hydrolysis)" },
      { f: "Alcohol + concentrated H₂SO₄, heat →", b: "Alkene + water. Elimination (dehydration)" },
      { f: "Carboxylic acid + alcohol →", b: "Ester + water. Esterification. Concentrated H₂SO₄ catalyst, heat" },
      { f: "Alkane + Br₂ in sunlight →", b: "Haloalkane + HBr. Substitution (halogenation)" },
      { f: "Cracking", b: "Long alkane → shorter alkane + alkene (elimination). High temperature or a catalyst" },
      { f: "Intermolecular force in alcohols and carboxylic acids", b: "Hydrogen bonds (plus London forces)" },
      { f: "Intermolecular force in aldehydes, ketones, esters", b: "Dipole–dipole forces (plus London forces)" },
    ],
  },
  {
    id: "chem-rules",
    subj: "phys",
    name: "Chemistry rules of thumb",
    blurb: "Le Chatelier, indicators, cells: the short facts that earn quick marks.",
    cards: [
      { f: "Increase temperature at equilibrium", b: "The endothermic reaction is favoured" },
      { f: "Increase pressure at equilibrium", b: "The side with fewer moles of gas is favoured" },
      { f: "What changes Kc?", b: "Only temperature" },
      { f: "Effect of a catalyst on equilibrium", b: "None on the yield. Both rates increase equally; equilibrium is reached faster" },
      { f: "Indicator: strong acid + strong base", b: "Bromothymol blue" },
      { f: "Indicator: strong acid + weak base", b: "Methyl orange" },
      { f: "Indicator: weak acid + strong base", b: "Phenolphthalein" },
      { f: "pH of a base", b: "Find [OH⁻], then [H₃O⁺] = 10⁻¹⁴ ÷ [OH⁻], then pH = −log[H₃O⁺]" },
      { f: "OIL RIG", b: "Oxidation Is Loss (of electrons), Reduction Is Gain" },
      { f: "AN OX, RED CAT", b: "Oxidation at the anode, reduction at the cathode" },
      { f: "Which half-reaction is the cathode?", b: "The one with the more positive E° value. Read the numbers, not the position in the table" },
      { f: "E°cell", b: "E°cathode − E°anode. Never multiply E° by coefficients" },
      { f: "Electroplating a spoon with silver", b: "Spoon = cathode. Silver = anode. Electrolyte contains Ag⁺ ions" },
      { f: "Salt bridge function", b: "Completes the circuit and keeps the solutions electrically neutral" },
      { f: "Catalyst and activation energy", b: "A catalyst gives an alternative path with a lower activation energy" },
      { f: "Collision theory answer", b: "…so there are more effective collisions per unit time, so the rate increases" },
    ],
  },
  {
    id: "maths-must",
    subj: "maths",
    name: "Maths must-knows",
    blurb: "Things that are NOT on the information sheet.",
    cards: [
      { f: "sin 30°, cos 30°, tan 30°", b: "½ · √3/2 · 1/√3" },
      { f: "sin 45°, cos 45°, tan 45°", b: "1/√2 · 1/√2 · 1" },
      { f: "sin 60°, cos 60°, tan 60°", b: "√3/2 · ½ · √3" },
      { f: "CAST: which ratios are positive in each quadrant?", b: "Q1 All · Q2 Sin · Q3 Tan · Q4 Cos" },
      { f: "sin(180° − θ), cos(180° − θ), tan(180° − θ)", b: "sin θ · −cos θ · −tan θ" },
      { f: "sin(180° + θ), cos(180° + θ), tan(180° + θ)", b: "−sin θ · −cos θ · tan θ" },
      { f: "sin(360° − θ), cos(360° − θ), tan(360° − θ)", b: "−sin θ · cos θ · −tan θ (same as −θ)" },
      { f: "sin(90° − θ), cos(90° − θ)", b: "cos θ · sin θ" },
      { f: "sin(90° + θ), cos(90° + θ)", b: "cos θ · −sin θ" },
      { f: "The two identities not on the sheet", b: "tan θ = sin θ / cos θ · sin²θ + cos²θ = 1" },
      { f: "General solution: sin θ = k", b: "θ = ref + k·360° or θ = (180° − ref) + k·360°, k ∈ ℤ" },
      { f: "General solution: cos θ = k", b: "θ = ±ref + k·360°, k ∈ ℤ" },
      { f: "General solution: tan θ = k", b: "θ = ref + k·180°, k ∈ ℤ" },
      { f: "Nature of roots from Δ = b² − 4ac", b: "Δ &lt; 0 non-real · Δ = 0 equal real · Δ &gt; 0 unequal real (rational if a perfect square)" },
      { f: "Differentiate axⁿ", b: "anxⁿ⁻¹" },
      { f: "Turning points of a graph", b: "Solve f′(x) = 0" },
      { f: "Point of inflection of a cubic", b: "Solve f″(x) = 0" },
      { f: "Perpendicular lines", b: "m₁ × m₂ = −1" },
      { f: "Angle of inclination when m is negative", b: "θ = 180° + tan⁻¹(m)" },
      { f: "Quadratic pattern Tₙ = an² + bn + c", b: "2a = second difference · 3a + b = T₂ − T₁ · a + b + c = T₁" },
      { f: "Number of terms from k = p to k = q", b: "q − p + 1" },
      { f: "When does S∞ exist?", b: "When −1 &lt; r &lt; 1 (r ≠ 0)" },
      { f: "Outlier fences", b: "Below Q1 − 1,5 × IQR or above Q3 + 1,5 × IQR" },
      { f: "Independent events", b: "P(A and B) = P(A) × P(B)" },
      { f: "Mutually exclusive events", b: "P(A and B) = 0" },
      { f: "Standard deviation on the calculator", b: "STAT → 1-VAR, enter data, then σx (not sx)" },
      { f: "Calculator mode for trig", b: "DEG. Check it before every paper" },
    ],
  },
  {
    id: "geo-reasons",
    subj: "maths",
    name: "Geometry reasons",
    blurb: "The fact on the front, the accepted reason on the back.",
    cards: [
      { f: "The angle at the centre compared with the angle at the circumference (same arc)", b: "∠ at centre = 2 × ∠ at circumference" },
      { f: "The angle subtended by a diameter", b: "∠ in semi-circle (= 90°)" },
      { f: "Angles on the same arc, same side", b: "∠s in the same seg (they are equal)" },
      { f: "Opposite angles of a cyclic quad", b: "opp ∠s of cyclic quad (add up to 180°)" },
      { f: "Exterior angle of a cyclic quad", b: "ext ∠ of cyclic quad (= interior opposite angle)" },
      { f: "Tangent and radius at the point of contact", b: "tan ⊥ radius" },
      { f: "Two tangents drawn from the same point", b: "tans from common pt (equal lengths)" },
      { f: "Angle between a tangent and a chord", b: "tan chord theorem (= angle in the alternate segment)" },
      { f: "Line from centre perpendicular to a chord", b: "line from centre ⊥ to chord (bisects the chord)" },
      { f: "Line from centre to the midpoint of a chord", b: "line from centre to midpt of chord (⊥ to the chord)" },
      { f: "Line parallel to one side of a triangle", b: "line ∥ one side of △ / prop theorem (divides the other sides in proportion)" },
      { f: "Line joining the midpoints of two sides of a triangle", b: "midpt theorem (∥ third side and half its length)" },
      { f: "Triangles with all three angles equal", b: "|||△s or ∠∠∠ (sides are in proportion)" },
      { f: "Angles opposite equal sides in a triangle", b: "∠s opp equal sides" },
      { f: "Angles on a straight line", b: "∠s on a str line (= 180°)" },
      { f: "Angles around a point", b: "∠s around a pt (= 360°)" },
      { f: "Vertically opposite angles", b: "vert opp ∠s (equal)" },
      { f: "Exterior angle of a triangle", b: "ext ∠ of △ (= sum of the two interior opposite angles)" },
      { f: "Sum of the angles of a triangle", b: "sum of ∠s in △ (= 180°)" },
      { f: "Parallel lines: Z-shape angles", b: "alt ∠s; AB ∥ CD" },
      { f: "Parallel lines: F-shape angles", b: "corresp ∠s; AB ∥ CD" },
      { f: "Parallel lines: C-shape angles", b: "co-int ∠s; AB ∥ CD (add up to 180°)" },
      { f: "Proving a quad is cyclic: opposite angles add up to 180°", b: "converse opp ∠s of cyclic quad (opp ∠s suppl)" },
      { f: "Proving a line is a tangent: the angle between line and chord equals the angle in the alternate segment", b: "converse tan chord theorem" },
    ],
  },
];

const DECK = Object.fromEntries(DECKS.map((d) => [d.id, d]));
