// Generated by tools/make_papers.py from the DBE past-paper index. Do not edit by hand.
const PAPERS_SOURCE = "2026-09-13T11:16:00";
const DBE_LISTING = "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx";
const PAPERS = [
 {
  "key": "2026-jun",
  "year": 2026,
  "session": "jun",
  "label": "May/June 2026",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=kYUGqKu-kwU%3d&tabid=5956&portalid=0&mid=15143",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=ODUkPQMn8_s%3d&tabid=5956&portalid=0&mid=15143",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=Pw1pjPEHmfc%3d&tabid=5956&portalid=0&mid=15143",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=8iQHJQchL_Y%3d&tabid=5956&portalid=0&mid=15143",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=b9jUTYuUQt4%3d&tabid=5956&portalid=0&mid=15143"
  },
  "phys": {
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=u5VMesdHqFU%3d&tabid=5956&portalid=0&mid=15146",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=Ni4kQJNozd0%3d&tabid=5956&portalid=0&mid=15146"
  }
 },
 {
  "key": "2025-nov",
  "year": 2025,
  "session": "nov",
  "label": "November 2025",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=nmr9-QLmN-s%3d&tabid=5742&portalid=0&mid=14845",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=8t-92qfBEV0%3d&tabid=5742&portalid=0&mid=14845",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=JM4biRg1OIk%3d&tabid=5742&portalid=0&mid=14845",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=0Hh6qly8lfU%3d&tabid=5742&portalid=0&mid=14845",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=lMX4KlIrUCs%3d&tabid=5742&portalid=0&mid=14845"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=hF7ax9AbzOw%3d&tabid=5742&portalid=0&mid=14848",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=oWZB83JVXE0%3d&tabid=5742&portalid=0&mid=14848",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=xvxkhSquue4%3d&tabid=5742&portalid=0&mid=14848",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=OpuzjBocaqw%3d&tabid=5742&portalid=0&mid=14848"
  }
 },
 {
  "key": "2025-jun",
  "year": 2025,
  "session": "jun",
  "label": "May/June 2025",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=vIwiaYq_GGU%3d&tabid=5475&portalid=0&mid=14244",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=FajC5X24OAc%3d&tabid=5475&portalid=0&mid=14244",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=9c8E54_peto%3d&tabid=5475&portalid=0&mid=14244",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=j-cLh7741Wk%3d&tabid=5475&portalid=0&mid=14244",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=e5e465cAoTA%3d&tabid=5475&portalid=0&mid=14244"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=to7vKFmBme4%3d&tabid=5475&portalid=0&mid=14247",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=mvizqI025HM%3d&tabid=5475&portalid=0&mid=14247",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=quzLyoK4HRA%3d&tabid=5475&portalid=0&mid=14247",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=nZ6nYkClxFU%3d&tabid=5475&portalid=0&mid=14247"
  }
 },
 {
  "key": "2024-nov",
  "year": 2024,
  "session": "nov",
  "label": "November 2024",
  "page": "https://www.education.gov.za/2024NSCNovemberpastpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=bO2LGxnHL_M%3d&tabid=5193&portalid=0&mid=13724",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=ycHWvBVvV2M%3d&tabid=5193&portalid=0&mid=13724",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=8W2dAxBUTQA%3d&tabid=5193&portalid=0&mid=13724",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=0DIM92_2Vu8%3d&tabid=5193&portalid=0&mid=13724",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=D_T4clPBpkk%3d&tabid=5193&portalid=0&mid=13724"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=ZxN41kEGHhI%3d&tabid=5193&portalid=0&mid=13728",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=jKqWYBbucS4%3d&tabid=5193&portalid=0&mid=13728",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=8rVrLl89rfM%3d&tabid=5193&portalid=0&mid=13728",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=4GvIWeAkK8U%3d&tabid=5193&portalid=0&mid=13728"
  }
 },
 {
  "key": "2024-jun",
  "year": 2024,
  "session": "jun",
  "label": "May/June 2024",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=01EQ1rKhQYw%3d&tabid=4933&portalid=0&mid=13146",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=RNNEcymfibQ%3d&tabid=4933&portalid=0&mid=13146",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=CsNcmi8-trM%3d&tabid=4933&portalid=0&mid=13146",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=hmseEn24qZI%3d&tabid=4933&portalid=0&mid=13146",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=LhWLj4xwFNo%3d&tabid=4933&portalid=0&mid=13146"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=m9pJHmW-bek%3d&tabid=4933&portalid=0&mid=13149",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=hMpdRUVbBVE%3d&tabid=4933&portalid=0&mid=13149",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=xFHHWbrK80I%3d&tabid=4933&portalid=0&mid=13149",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=0jBTW_KEhkM%3d&tabid=4933&portalid=0&mid=13149"
  }
 },
 {
  "key": "2023-nov",
  "year": 2023,
  "session": "nov",
  "label": "November 2023",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/2023NSCNovemberpastpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=Zo-o-hb_2zA%3d&tabid=4682&portalid=0&mid=12681",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=Zoios-rCurI%3d&tabid=4682&portalid=0&mid=12681",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=M_7mZq2zE5o%3d&tabid=4682&portalid=0&mid=12681",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=0RJSBcYBmhA%3d&tabid=4682&portalid=0&mid=12681",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=ViEtlf4659c%3d&tabid=4682&portalid=0&mid=12681"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=Gs2cDJBpRR0%3d&tabid=4682&portalid=0&mid=12685",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=oTJzzXEU6Ng%3d&tabid=4682&portalid=0&mid=12685",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=1JdWi95UKbY%3d&tabid=4682&portalid=0&mid=12685",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=6g6X4xphO7I%3d&tabid=4682&portalid=0&mid=12685"
  }
 },
 {
  "key": "2023-jun",
  "year": 2023,
  "session": "jun",
  "label": "May/June 2023",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=tTihfM04RXU%3d&tabid=4504&portalid=0&mid=12317",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=-Jidqi5J8YU%3d&tabid=4504&portalid=0&mid=12317",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=G2Yz_FbwMjk%3d&tabid=4504&portalid=0&mid=12317",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=QglalUTQMaw%3d&tabid=4504&portalid=0&mid=12317",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=lKqjE45EcJE%3d&tabid=4504&portalid=0&mid=12317"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=3s86L5Ok4Ds%3d&tabid=4504&portalid=0&mid=12321",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=Yak0VdHytZc%3d&tabid=4504&portalid=0&mid=12321",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=aLPZ0KC5LZU%3d&tabid=4504&portalid=0&mid=12321",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=fQHTbH4T2fo%3d&tabid=4504&portalid=0&mid=12321"
  }
 },
 {
  "key": "2022-nov",
  "year": 2022,
  "session": "nov",
  "label": "November 2022",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=qex2-H-2Syc%3d&tabid=3294&portalid=0&mid=10986",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=DqfP-i10rEE%3d&tabid=3294&portalid=0&mid=10986",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=Juy5nA5N3fM%3d&tabid=3294&portalid=0&mid=10986",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=var8F7VpOmU%3d&tabid=3294&portalid=0&mid=10986",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=gytAGGPYSc8%3d&tabid=3294&portalid=0&mid=10986"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=_7CRVUkWGMA%3d&tabid=3294&portalid=0&mid=10990",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=5l5vQTQBaU4%3d&tabid=3294&portalid=0&mid=10990",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=DFAi1wMTvCg%3d&tabid=3294&portalid=0&mid=10990",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=1GNWZdT8oLQ%3d&tabid=3294&portalid=0&mid=10990"
  }
 },
 {
  "key": "2022-jun",
  "year": 2022,
  "session": "jun",
  "label": "May/June 2022",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=YcvUaN-79_M%3d&tabid=3138&portalid=0&mid=10574",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=9vgMSe2r52w%3d&tabid=3138&portalid=0&mid=10574",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=TYv9teRDIwc%3d&tabid=3138&portalid=0&mid=10574",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=iMIvxdxJCEs%3d&tabid=3138&portalid=0&mid=10574",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=ias3gDQea2c%3d&tabid=3138&portalid=0&mid=10574"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=VLzSkzZUFDY%3d&tabid=3138&portalid=0&mid=10577",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=o_2N5ChGOm8%3d&tabid=3138&portalid=0&mid=10577",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=bE8UM3kiKvo%3d&tabid=3138&portalid=0&mid=10577",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=q9BK62Npx-I%3d&tabid=3138&portalid=0&mid=10577"
  }
 },
 {
  "key": "2021-nov",
  "year": 2021,
  "session": "nov",
  "label": "November 2021",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=mA7N3HwvvaE%3d&tabid=2922&portalid=0&mid=10135",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=jgMJbW3Aa0o%3d&tabid=2922&portalid=0&mid=10135",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=sGgq9FNv0lQ%3d&tabid=2922&portalid=0&mid=10135",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=s7hK0H8bqPM%3d&tabid=2922&portalid=0&mid=10135",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=LJo4MZ4DRZM%3d&tabid=2922&portalid=0&mid=10135"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=oI4BAzXUMNA%3d&tabid=2922&portalid=0&mid=10138",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=unBWzCuezsM%3d&tabid=2922&portalid=0&mid=10138",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=gmvfHOKfxws%3d&tabid=2922&portalid=0&mid=10138",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=VCtYr0giXYw%3d&tabid=2922&portalid=0&mid=10138"
  }
 },
 {
  "key": "2021-jun",
  "year": 2021,
  "session": "jun",
  "label": "May/June 2021",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=VGY9gE7yrqs%3d&tabid=2837&portalid=0&mid=9915",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=lmRtO5TrNn0%3d&tabid=2837&portalid=0&mid=9915",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=74QPUYzp2gI%3d&tabid=2837&portalid=0&mid=9915",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=7HD9X7z3SWA%3d&tabid=2837&portalid=0&mid=9915",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=_Uf6aXgNhio%3d&tabid=2837&portalid=0&mid=9915"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=9IngEp8UnPg%3d&tabid=2837&portalid=0&mid=9918",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=fwuKbvYVeLA%3d&tabid=2837&portalid=0&mid=9918",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=kg9Cg7DlpSQ%3d&tabid=2837&portalid=0&mid=9918",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=S7FjUU2IRHo%3d&tabid=2837&portalid=0&mid=9918"
  }
 },
 {
  "key": "2020-nov",
  "year": 2020,
  "session": "nov",
  "label": "November 2020",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=bpqGfOO_0wA%3d&tabid=2702&portalid=0&mid=9632",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=f-OMZa2HZ5U%3d&tabid=2702&portalid=0&mid=9632",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=FU-0n3tYUzs%3d&tabid=2702&portalid=0&mid=9632",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=R9cpC35sw60%3d&tabid=2702&portalid=0&mid=9632",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=P7kQcnNxRHY%3d&tabid=2702&portalid=0&mid=9632"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=xUQ6Zo6wIpI%3d&tabid=2702&portalid=0&mid=9635",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=65cL9MczvtQ%3d&tabid=2702&portalid=0&mid=9635",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=l5Q6JxAbkZ0%3d&tabid=2702&portalid=0&mid=9635",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=1MOdP9_gqm4%3d&tabid=2702&portalid=0&mid=9635"
  }
 },
 {
  "key": "2019-nov",
  "year": 2019,
  "session": "nov",
  "label": "November 2019",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=RQxkQUKqBaU%3d&tabid=2556&portalid=0&mid=8994",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=Tno439ZyBcU%3d&tabid=2556&portalid=0&mid=8994",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=s6HzylxEHVo%3d&tabid=2556&portalid=0&mid=8994",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=n-F98_w5Zig%3d&tabid=2556&portalid=0&mid=8994",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=DtEIXt8fp_E%3d&tabid=2556&portalid=0&mid=8994"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=Xcl5pu2aqPQ%3d&tabid=2556&portalid=0&mid=8990",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=81kc5rUaNFk%3d&tabid=2556&portalid=0&mid=8990",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=mU3ifOrbHG8%3d&tabid=2556&portalid=0&mid=8990",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=LLMMn13si1c%3d&tabid=2556&portalid=0&mid=8990"
  }
 },
 {
  "key": "2018-nov",
  "year": 2018,
  "session": "nov",
  "label": "November 2018",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=lS1oTeOCp7A%3d&tabid=2268&portalid=0&mid=8402",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=QE2-jAQgyWo%3d&tabid=2268&portalid=0&mid=8402",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=ABGQ68K1-V0%3d&tabid=2268&portalid=0&mid=8402",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=oaZUa6tkOeI%3d&tabid=2268&portalid=0&mid=8402",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=JGqaMbWx7XA%3d&tabid=2268&portalid=0&mid=8402"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=8saVtMjM6Qc%3d&tabid=2268&portalid=0&mid=8405",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=XrafsttgVzU%3d&tabid=2268&portalid=0&mid=8405",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=KHDS8lZFxBE%3d&tabid=2268&portalid=0&mid=8405",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=R9TOAKfwYQ4%3d&tabid=2268&portalid=0&mid=8405"
  }
 },
 {
  "key": "2018-jun",
  "year": 2018,
  "session": "jun",
  "label": "May/June 2018",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=Cj_uQtWiCN8%3d&tabid=2182&portalid=0&mid=8262",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=YyC1A8I6gVM%3d&tabid=2182&portalid=0&mid=8262",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=CzWQocU9ITs%3d&tabid=2182&portalid=0&mid=8262",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=Z7FtKvRZEDI%3d&tabid=2182&portalid=0&mid=8262",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=CvUTrHTn3is%3d&tabid=2182&portalid=0&mid=8262"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=rFjIYf95_Sk%3d&tabid=2182&portalid=0&mid=8266",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=moz7pmDYTYw%3d&tabid=2182&portalid=0&mid=8266",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=DyK78C2CsTo%3d&tabid=2182&portalid=0&mid=8266",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=MaFLMkH0zK4%3d&tabid=2182&portalid=0&mid=8266"
  }
 },
 {
  "key": "2017-nov",
  "year": 2017,
  "session": "nov",
  "label": "November 2017",
  "page": "https://www.education.gov.za/Home/2017NSCNovemberpastpapers.aspx",
  "phys": {
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=GDvpKcfxROs%3D&tabid=1856&portalid=0&mid=7354"
  },
  "maths": {}
 },
 {
  "key": "2017-mar",
  "year": 2017,
  "session": "mar",
  "label": "Feb/March 2017",
  "page": "https://www.education.gov.za/Curriculum/NationalSeniorCertificate(NSC)Examinations/NSCPastExaminationpapers.aspx",
  "maths": {
   "ab": "https://www.education.gov.za/LinkClick.aspx?fileticket=pVzNoI61WvU%3d&tabid=1608&portalid=0&mid=6389",
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=439OVfCbiZQ%3d&tabid=1608&portalid=0&mid=6389",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=ZGGQ0ej5wtY%3d&tabid=1608&portalid=0&mid=6389",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=OrlzXEgx8SE%3d&tabid=1608&portalid=0&mid=6389",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=iREWBLhU0kg%3d&tabid=1608&portalid=0&mid=6389"
  },
  "phys": {
   "p2": "https://www.education.gov.za/LinkClick.aspx?fileticket=vkqyGS7LnSQ%3d&tabid=1608&portalid=0&mid=6393",
   "p1": "https://www.education.gov.za/LinkClick.aspx?fileticket=fX0B3Oa59C8%3d&tabid=1608&portalid=0&mid=6393",
   "m2": "https://www.education.gov.za/LinkClick.aspx?fileticket=40GlODW4S0c%3d&tabid=1608&portalid=0&mid=6393",
   "m1": "https://www.education.gov.za/LinkClick.aspx?fileticket=_qpmS8m0NWI%3d&tabid=1608&portalid=0&mid=6393"
  }
 }
];
