// Physical Sciences content. Paper 1 = Physics, Paper 2 = Chemistry.
// Definitions follow the wording of the DBE exam guidelines as closely as
// possible, because definitions are marked word for word.

const PHYS_TOPICS = [
  // ───────────────────────────── PAPER 1: PHYSICS ─────────────────────────────
  {
    id: "p-newton",
    subj: "phys",
    paper: 1,
    name: "Newton's laws & gravitation",
    marks: "≈ 25",
    where: "Paper 1 · usually Question 2 (after the multiple choice)",
    level: "core",
    hook: "Definitions, free-body diagrams and Fnet = ma earn most of these marks. The same question shapes (incline, two blocks and a rope, friction) repeat every year.",
    videos: [
      V("T1ONXrPQN8E", "Newton's Laws grade 11 and 12: Watch this before doing calculations!", "The basics you need before any calculation."),
      V("62gmFI7VB8g", "Grade 12 Physical Science: Newton's Laws - Forces on an inclined plane", "Inclines: which component of weight goes where."),
      V("ExvwFwQe1us", "Newton's Second Law of Motion Grade 11 and 12 Physics", "Fnet = ma for single and connected objects."),
      V("TcgBamEa4W8", "Newton's Law of Universal Gravitation Grade 11 and 12 Physics", "The gravitation definition and formula with examples."),
    ],
    ideas: [
      "A <b>free-body diagram</b> is a dot with arrows for every force acting on the object, each arrow labelled.",
      "<b>Fnet = ma</b>: add up all forces along the direction of motion (with signs), set it equal to mass × acceleration.",
      "On an <b>incline</b>, weight splits into two parts: mg sin θ down the slope and mg cos θ into the slope. The normal force balances mg cos θ.",
      "<b>Friction</b> always opposes motion: f = μN.",
      "Objects joined by a rope have the same acceleration. Write Fnet = ma for each object separately and solve.",
      "Gravitational force halves the distance → force × 4. Double the distance → force ÷ 4.",
    ],
    defs: [
      ["Newton's first law", "A body will remain in its state of rest or motion at constant velocity unless a non-zero resultant/net force acts on it."],
      ["Newton's second law", "When a resultant/net force acts on an object, the object will accelerate in the direction of the net force at an acceleration directly proportional to the force and inversely proportional to the mass of the object."],
      ["Newton's third law", "When object A exerts a force on object B, object B simultaneously exerts an oppositely directed force of equal magnitude on object A."],
      ["Newton's law of universal gravitation", "Each body in the universe attracts every other body with a force that is directly proportional to the product of their masses and inversely proportional to the square of the distance between their centres."],
      ["Normal force", "The perpendicular force exerted by a surface on an object in contact with it."],
      ["Frictional force", "The force that opposes the motion of an object and acts parallel to the surface."],
      ["Weight", "The gravitational force the Earth exerts on any object on or near its surface."],
      ["Inertia", "The property of an object that causes it to resist a change in its state of rest or uniform motion."],
    ],
    formulas: [
      { label: "Newton's second law", f: "F<sub>net</sub> = ma", sheet: true },
      { label: "Weight", f: "w = mg", sheet: true },
      { label: "Friction", f: "f<sub>k</sub> = μ<sub>k</sub>N · f<sub>s</sub>(max) = μ<sub>s</sub>N", sheet: true },
      { label: "Gravitation", f: `F = ${fr("Gm₁m₂", "r²")} · g = ${fr("GM", "r²")}`, sheet: true },
      { label: "Incline components", f: "w<sub>∥</sub> = mg sin θ · w<sub>⊥</sub> = mg cos θ", sheet: false },
    ],
    method: [
      "Draw the free-body diagram: arrows start on the dot, each labelled (weight w / F<sub>g</sub>, normal N, friction f, tension T, applied F).",
      "Choose a positive direction, usually the direction of motion.",
      "Write F<sub>net</sub> = ma, then list the forces: e.g. F − f = ma. For each object separately if there are two.",
      "Substitute and solve. Give the direction with any force or acceleration answer.",
    ],
    examples: [
      {
        q: "A 5 kg block is pulled horizontally with 30 N. Friction is 10 N. Find the acceleration.",
        lines: [`F<sub>net</sub> = ma ${tk}`, `30 − 10 = 5a ${tk}`, `a = 4 m·s⁻² in the direction of the pull ${tk}`],
      },
      {
        q: "Two blocks (3 kg and 2 kg) are joined by a string on a frictionless surface. A 20 N force pulls the 3 kg block. Find the acceleration and the tension.",
        lines: [
          `Whole system: 20 = (3 + 2)a, so a = 4 m·s⁻² ${tk}`,
          `2 kg block: T = ma = 2 × 4 = 8 N ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Drawing F<sub>net</sub> or “ma” as a force on the free-body diagram. It's not a force.",
      "Forgetting friction, or letting arrows float away from the dot.",
      "Using N = mg on an incline. It's N = mg cos θ.",
      "Forgetting to square r in the gravitation formula, or leaving r in km.",
      "Leaving out the direction in the final answer.",
    ],
    practice: [
      { q: "Net force on a 1 200 kg car accelerating at 2,5 m·s⁻²?", a: "F<sub>net</sub> = ma = 1 200 × 2,5 = 3 000 N in the direction of motion" },
      { q: "μ<sub>k</sub> = 0,2 for a 10 kg box on a horizontal floor. Kinetic friction?", a: "f = μN = 0,2 × 10 × 9,8 = 19,6 N" },
      { q: "Both masses double and the distance between them doubles. What happens to F?", a: "F × 2 × 2 ÷ 2² = F. It stays the same." },
      { q: "A 2 kg block slides down a frictionless 30° incline. Acceleration?", a: "a = g sin 30° = 9,8 × 0,5 = 4,9 m·s⁻² down the slope" },
      { q: "State Newton's third law.", a: "When object A exerts a force on object B, object B simultaneously exerts an oppositely directed force of equal magnitude on object A." },
    ],
    yt: "grade 12 newtons laws exam question physical sciences",
  },

  {
    id: "p-momentum",
    subj: "phys",
    paper: 1,
    name: "Momentum & impulse",
    marks: "≈ 15",
    where: "Paper 1 · usually Question 3 or 4",
    level: "gold",
    hook: "Very formulaic: two definitions, one conservation equation and one impulse equation. The only trap is the sign of the velocity.",
    videos: [
      V("JOyL0KJRe0g", "Momentum grade 12: Introduction", "What momentum is and the direction rule."),
      V("SSUo3FSQCD8", "Grade 12 Impulse and impulse momentum theorem", "Impulse, F<sub>net</sub>Δt = Δp, and why airbags work."),
      V("jctBwmUTJ9w", "Momentum Grade 12: Exam", "An exam question from start to finish.", "exam"),
    ],
    ideas: [
      "<b>Momentum</b> p = mv. It's a vector, so direction matters.",
      "Pick one direction as positive. A velocity the other way is <b>negative</b>. This is where most marks are lost.",
      "In a collision or explosion in an isolated system, <b>total momentum before = total momentum after</b>.",
      "<b>Impulse</b> = F<sub>net</sub>Δt = change in momentum. A longer contact time means a smaller force (airbags, crumple zones, bending your knees).",
      "<b>Elastic</b> collision: kinetic energy is also conserved. Check by calculating total E<sub>k</sub> before and after.",
    ],
    defs: [
      ["Momentum", "The product of an object's mass and its velocity."],
      ["Newton's second law in terms of momentum", "The net (or resultant) force acting on an object is equal to the rate of change of momentum of the object (in the direction of the net force)."],
      ["Principle of conservation of linear momentum", "The total linear momentum of an isolated system remains constant (is conserved)."],
      ["Isolated system", "A system on which the resultant/net external force is zero."],
      ["Impulse", "The product of the net force acting on an object and the time the net force acts on the object."],
      ["Elastic collision", "A collision in which both total momentum and total kinetic energy are conserved."],
      ["Inelastic collision", "A collision in which only total momentum is conserved (total kinetic energy is not conserved)."],
    ],
    formulas: [
      { label: "Momentum", f: "p = mv", sheet: true },
      { label: "Impulse", f: "F<sub>net</sub>Δt = Δp = mv<sub>f</sub> − mv<sub>i</sub>", sheet: true },
      { label: "Conservation", f: "m₁v<sub>i1</sub> + m₂v<sub>i2</sub> = m₁v<sub>f1</sub> + m₂v<sub>f2</sub>", sheet: false },
      { label: "Kinetic energy", f: "E<sub>k</sub> = ½mv²", sheet: true },
    ],
    method: [
      "Choose a positive direction and write it down (e.g. “East is positive”).",
      "Collision or explosion: Σp<sub>before</sub> = Σp<sub>after</sub>. Substitute with signs.",
      "Impulse: Δp = m(v<sub>f</sub> − v<sub>i</sub>). A ball that rebounds changes sign.",
      "Final answer: magnitude + unit + direction.",
      "Elastic or not? Compare ½mv² totals before and after.",
    ],
    examples: [
      {
        q: "A 2 kg ball moving east at 3 m·s⁻¹ hits a stationary 1 kg ball. The 2 kg ball then moves east at 1 m·s⁻¹. Find the velocity of the 1 kg ball. Is the collision elastic?",
        lines: [
          `Σp<sub>before</sub> = Σp<sub>after</sub> ${tk}`,
          `(2)(3) + (1)(0) = (2)(1) + (1)v ${tk}`,
          `v = 4 m·s⁻¹ east ${tk}`,
          `E<sub>k</sub> before = ½(2)(3²) = 9 J. E<sub>k</sub> after = ½(2)(1²) + ½(1)(4²) = 9 J ${tk}`,
          `Kinetic energy is conserved, so the collision is elastic ${tk}`,
        ],
      },
      {
        q: "A 0,15 kg ball hits a wall at 20 m·s⁻¹ and rebounds at 15 m·s⁻¹. Contact lasts 0,05 s. Find the force of the wall on the ball.",
        lines: [
          "Towards the wall is positive.",
          `F<sub>net</sub>Δt = m(v<sub>f</sub> − v<sub>i</sub>) ${tk}`,
          `F(0,05) = 0,15(−15 − 20) ${tk}`,
          `F = −105 N, so 105 N away from the wall ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Forgetting the negative sign for a velocity in the opposite direction (rebounds, recoil).",
      "Giving a momentum, impulse or velocity without a direction.",
      "Adding speeds instead of momenta.",
      "Assuming kinetic energy is conserved without checking.",
    ],
    practice: [
      { q: "Momentum of a 1 500 kg car moving at 20 m·s⁻¹ north?", a: "p = 1 500 × 20 = 30 000 kg·m·s⁻¹ north" },
      { q: "A 4 kg gun fires a 0,01 kg bullet at 400 m·s⁻¹. Recoil velocity?", a: "0 = (0,01)(400) + 4v → v = −1 m·s⁻¹, so 1 m·s⁻¹ backwards" },
      { q: "A 2 kg trolley at 4 m·s⁻¹ hits and sticks to a stationary 2 kg trolley. Final velocity? Elastic?", a: "8 = 4v → v = 2 m·s⁻¹. E<sub>k</sub> before 16 J, after 8 J: inelastic" },
      { q: "Explain why airbags reduce injuries.", a: "They increase the contact time Δt. For the same change in momentum, F<sub>net</sub> = Δp/Δt is smaller." },
      { q: "A 0,5 kg ball goes from 10 m·s⁻¹ to rest in 0,1 s. Force on it?", a: "Δp = 0,5(0 − 10) = −5 kg·m·s⁻¹. F = −5/0,1 = −50 N, so 50 N opposite to the motion" },
    ],
    yt: "grade 12 momentum impulse exam physical sciences",
  },

  {
    id: "p-vpm",
    subj: "phys",
    paper: 1,
    name: "Vertical projectile motion",
    marks: "≈ 15",
    where: "Paper 1 · usually Question 3 or 4",
    level: "core",
    hook: "Four equations of motion and one fact: the acceleration is always 9,8 m·s⁻² downwards. Pick a direction and never change it.",
    videos: [
      V("e01ClgdyD4s", "Grade 12 Vertical Projectile Motion: Introduction", "The key facts: g, the top point, time up = time down."),
      V("dGlmO6AvdEM", "Vertical Projectile Motion Graphs Grade 12 Physics", "Position, velocity and acceleration graphs."),
      V("05fJroMHBeg", "Vertical motion graphs: Grade 12 Physical Sciences questions", "Graph questions from exams.", "exam"),
    ],
    ideas: [
      "A <b>projectile</b> only has gravity acting on it. Its acceleration is 9,8 m·s⁻² <b>downwards</b>, all the time, even at the top.",
      "At the highest point the velocity is <b>0</b> (but the acceleration is still 9,8 m·s⁻² down).",
      "Time to go up = time to come back down to the same height.",
      "<b>Velocity–time graph</b>: a straight line with gradient g. It crosses the time axis at the top point.",
      "<b>Position–time graph</b>: a parabola. <b>Acceleration–time</b>: a horizontal line.",
    ],
    defs: [
      ["Projectile", "An object upon which the only force acting is the force of gravity."],
      ["Free fall", "Motion during which the only force acting on an object is the gravitational force."],
    ],
    formulas: [
      { label: "Velocity", f: "v<sub>f</sub> = v<sub>i</sub> + aΔt", sheet: true },
      { label: "Displacement", f: "Δy = v<sub>i</sub>Δt + ½aΔt²", sheet: true },
      { label: "No time", f: "v<sub>f</sub>² = v<sub>i</sub>² + 2aΔy", sheet: true },
      { label: "Average velocity", f: `Δy = (${fr("v<sub>i</sub> + v<sub>f</sub>", "2")})Δt`, sheet: true },
    ],
    method: [
      "Choose up or down as positive and write it down. Then a = −9,8 (up positive) or +9,8 (down positive).",
      "List what you know: v<sub>i</sub>, v<sub>f</sub>, a, Δt, Δy. At the top, v<sub>f</sub> = 0. Dropped means v<sub>i</sub> = 0.",
      "Pick the equation with only one unknown.",
      "Substitute with signs, solve, give units and direction.",
    ],
    examples: [
      {
        q: "A ball is thrown straight up at 14,7 m·s⁻¹. Find the time to the top and the maximum height.",
        lines: [
          "Up is positive, a = −9,8 m·s⁻².",
          `v<sub>f</sub> = v<sub>i</sub> + aΔt: 0 = 14,7 − 9,8Δt ${tk}`,
          `Δt = 1,5 s ${tk}`,
          `v<sub>f</sub>² = v<sub>i</sub>² + 2aΔy: 0 = 14,7² + 2(−9,8)Δy ${tk}`,
          `Δy = 11,03 m ${tk}`,
        ],
      },
      {
        q: "A stone is dropped from 20 m. How fast does it hit the ground?",
        lines: [
          "Down is positive, a = 9,8 m·s⁻², v<sub>i</sub> = 0.",
          `v<sub>f</sub>² = 0 + 2(9,8)(20) ${tk}`,
          `v<sub>f</sub> = 19,80 m·s⁻¹ downwards ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Mixing signs: using +9,8 when up is positive.",
      "Saying the acceleration at the top is zero.",
      "Using g = 10. Use 9,8 m·s⁻² from the data sheet.",
      "Forgetting that the displacement is 0 when the ball returns to the thrower's hand.",
    ],
    practice: [
      { q: "A stone is dropped from a cliff and hits the ground after 3 s. Height of the cliff?", a: "Δy = ½(9,8)(3²) = 44,1 m" },
      { q: "Velocity and acceleration at the maximum height?", a: "Velocity 0 m·s⁻¹. Acceleration 9,8 m·s⁻² downwards" },
      { q: "A ball is thrown up at 20 m·s⁻¹. Maximum height?", a: "0 = 20² − 2(9,8)Δy → Δy = 20,41 m" },
      { q: "Velocity 2 s after being dropped?", a: "v = 0 + 9,8 × 2 = 19,6 m·s⁻¹ downwards" },
    ],
    yt: "grade 12 vertical projectile motion exam question",
  },

  {
    id: "p-wep",
    subj: "phys",
    paper: 1,
    name: "Work, energy & power",
    marks: "≈ 15–20",
    where: "Paper 1 · usually Question 5",
    level: "core",
    hook: "Four definitions, W = FΔx cos θ, and one of two energy equations. Most questions follow the same pattern.",
    videos: [
      V("oatwdRW1klg", "Work Energy Power Grade 12 Physics", "Work done and the cos θ part."),
      V("GIXvqsMgTAU", "Work Energy Theorem Grade 12 Work Energy Power", "W<sub>net</sub> = ΔE<sub>k</sub> in use."),
      V("8L3pS8Cf9CU", "Work, Energy and Power grade 12: Exam", "A full exam question.", "exam"),
    ],
    ideas: [
      "<b>Work</b> = force × displacement × cos θ, where θ is the angle between the force and the displacement.",
      "Friction does <b>negative</b> work (θ = 180°).",
      "<b>Work–energy theorem</b>: the net work done equals the change in kinetic energy.",
      "No friction? Mechanical energy is conserved: mgh + ½mv² stays the same.",
      "With friction or an applied force, use W<sub>nc</sub> = ΔE<sub>k</sub> + ΔE<sub>p</sub>.",
      "<b>Power</b> is how fast work is done. At constant speed, P = Fv.",
    ],
    defs: [
      ["Work done on an object by a force", "The product of the magnitude of the force and the magnitude of the displacement in the direction of the force."],
      ["Work-energy theorem", "The work done by a net force on an object is equal to the change in the kinetic energy of the object."],
      ["Conservative force", "A force for which the work done in moving an object between two points is independent of the path taken."],
      ["Non-conservative force", "A force for which the work done in moving an object between two points depends on the path taken."],
      ["Principle of conservation of mechanical energy", "The total mechanical energy (sum of gravitational potential energy and kinetic energy) in an isolated system remains constant."],
      ["Power", "The rate at which work is done or energy is expended."],
    ],
    formulas: [
      { label: "Work", f: "W = FΔx cos θ", sheet: true },
      { label: "Energy", f: "E<sub>p</sub> = mgh · E<sub>k</sub> = ½mv²", sheet: true },
      { label: "Work–energy theorem", f: "W<sub>net</sub> = ΔE<sub>k</sub>", sheet: true },
      { label: "Non-conservative forces", f: "W<sub>nc</sub> = ΔE<sub>k</sub> + ΔE<sub>p</sub>", sheet: true },
      { label: "Power", f: `P = ${fr("W", "Δt")} · P<sub>ave</sub> = Fv<sub>ave</sub>`, sheet: true },
    ],
    method: [
      "Draw a quick free-body diagram so you know every force doing work.",
      "Work by one force: W = FΔx cos θ. θ is between that force and the direction of movement.",
      "No friction: (mgh + ½mv²)<sub>start</sub> = (mgh + ½mv²)<sub>end</sub>.",
      "With friction: W<sub>nc</sub> = ΔE<sub>k</sub> + ΔE<sub>p</sub>, where W<sub>nc</sub> includes friction (negative) and any applied force.",
      "Power at constant speed: the driving force equals the total resistance, then P = Fv.",
    ],
    examples: [
      {
        q: "A 50 N force at 30° to the horizontal pulls a box 10 m along the floor. Work done by the force?",
        lines: [`W = FΔx cos θ ${tk}`, `W = (50)(10) cos 30° ${tk}`, `W = 433,01 J ${tk}`],
      },
      {
        q: "A 2 kg ball is dropped from 5 m. Ignoring air resistance, find its speed at the ground.",
        lines: [
          `E<sub>mech top</sub> = E<sub>mech bottom</sub>: mgh = ½mv² ${tk}`,
          `(2)(9,8)(5) = ½(2)v² ${tk}`,
          `v = 9,90 m·s⁻¹ ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Forgetting cos θ, or using the angle with the wrong line.",
      "Making the work done by friction positive.",
      "On a slope: using W<sub>net</sub> = ΔE<sub>k</sub> but forgetting the work done by gravity.",
      "Mixing up J (work, energy) and W (power).",
    ],
    practice: [
      { q: "Kinetic energy of a 0,5 kg ball at 4 m·s⁻¹?", a: "½ × 0,5 × 4² = 4 J" },
      { q: "Work done by a 20 N friction force over 5 m?", a: "W = 20 × 5 × cos 180° = −100 J" },
      { q: "A 60 kg learner climbs 3 m of stairs in 4 s. Power?", a: "W = mgh = 60 × 9,8 × 3 = 1 764 J. P = 1 764 ÷ 4 = 441 W" },
      { q: "A car moves at a constant 25 m·s⁻¹ against 1 200 N of resistance. Power of the engine?", a: "P = Fv = 1 200 × 25 = 30 000 W" },
      { q: "Define a conservative force.", a: "A force for which the work done in moving an object between two points is independent of the path taken." },
    ],
    yt: "grade 12 work energy power exam question",
  },

  {
    id: "p-doppler",
    subj: "phys",
    paper: 1,
    name: "Doppler effect",
    marks: "≈ 10",
    where: "Paper 1 · usually Question 6",
    level: "gold",
    hook: "One definition and one formula. The only decision is the sign in the formula. One of the fastest topics to learn.",
    videos: [
      V("Qr0zVvyFAz8", "The Doppler Effect Grade 12 Introduction and formula", "The formula and when to use + or −."),
      V("MbVvbHSFNeY", "The Doppler Effect grade 12 Practice Questions", "Practice with the signs."),
      V("wrcQJtaOlQA", "Doppler Effect grade 12: Exam", "An exam question worked out.", "exam"),
    ],
    ideas: [
      "When a sound source moves <b>towards</b> you, you hear a <b>higher</b> frequency. Moving <b>away</b>: lower.",
      "In the formula, a source moving towards the listener gives v − v<sub>s</sub> in the denominator (smaller bottom, bigger answer).",
      "Most questions have a stationary listener, so v<sub>L</sub> = 0.",
      "<b>Red shift</b>: light from stars moving away from us shifts to lower frequencies (longer wavelength). Evidence that the universe is expanding.",
      "Uses: ultrasound to measure blood flow (e.g. a baby's heartbeat), radar speed traps.",
    ],
    defs: [
      ["Doppler effect", "The change in frequency (or pitch) of the sound detected by a listener because the sound source and the listener have different velocities relative to the medium of sound propagation."],
    ],
    formulas: [
      { label: "Doppler", f: `f<sub>L</sub> = ${fr("v ± v<sub>L</sub>", "v ± v<sub>s</sub>")} f<sub>s</sub>`, sheet: true },
      { label: "Wave equation", f: "v = fλ", sheet: true },
      { label: "Signs", f: "Listener towards source: +v<sub>L</sub> · Source towards listener: −v<sub>s</sub> · Source away: +v<sub>s</sub>", sheet: false },
    ],
    method: [
      "Write the formula.",
      "Decide: is the source approaching (−v<sub>s</sub>) or moving away (+v<sub>s</sub>)?",
      "Substitute v (speed of sound, given in the question), v<sub>s</sub> and f<sub>s</sub>.",
      "Check your answer makes sense: approaching must be higher than f<sub>s</sub>.",
    ],
    examples: [
      {
        q: "An ambulance siren has a frequency of 500 Hz. It moves towards a stationary listener at 30 m·s⁻¹. Speed of sound 340 m·s⁻¹. What frequency does the listener hear?",
        lines: [
          `f<sub>L</sub> = ${fr("v ± v<sub>L</sub>", "v ± v<sub>s</sub>")} f<sub>s</sub> ${tk}`,
          `f<sub>L</sub> = ${fr("340 + 0", "340 − 30")} × 500 ${tk}`,
          `f<sub>L</sub> = 548,39 Hz ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Using the wrong sign for v<sub>s</sub>.",
      "Leaving the v out of the numerator.",
      "Mixing up the source and the listener.",
      "Saying red shift means the star is coming towards us.",
    ],
    practice: [
      { q: "An 800 Hz source moves away from a listener at 20 m·s⁻¹ (v = 340 m·s⁻¹). Heard frequency?", a: "f<sub>L</sub> = 340/(340 + 20) × 800 = 755,56 Hz" },
      { q: "A listener hears 850 Hz as a source approaches at 20 m·s⁻¹ (v = 340 m·s⁻¹). Find f<sub>s</sub>.", a: "850 = 340/320 × f<sub>s</sub> → f<sub>s</sub> = 800 Hz" },
      { q: "Why is light from a distant galaxy red-shifted?", a: "The galaxy is moving away from Earth, so the observed frequency decreases (wavelength increases)." },
      { q: "State the Doppler effect.", a: "The change in frequency (or pitch) of the sound detected by a listener because the sound source and the listener have different velocities relative to the medium of sound propagation." },
    ],
    yt: "grade 12 doppler effect exam question",
  },

  {
    id: "p-electrostatics",
    subj: "phys",
    paper: 1,
    name: "Electrostatics",
    marks: "≈ 15",
    where: "Paper 1 · usually Question 7",
    level: "core",
    hook: "Coulomb's law and electric field strength. Convert µC and nC correctly and you're most of the way there.",
    videos: [
      V("ngfkLMOQDms", "Coulomb's Law Electrostatics grade 11 and 12", "Coulomb's law with worked examples."),
      V("ozWaTaCZh_I", "Electric Fields Electrostatics grade 11 and 12 summary", "Electric fields and field-line drawings."),
    ],
    ideas: [
      "Like charges repel, unlike charges attract.",
      "Put only <b>sizes</b> of charges into the formula (no negative signs). Decide the direction from attraction or repulsion.",
      "Convert units: µC = × 10⁻⁶ C, nC = × 10⁻⁹ C, cm ÷ 100 = m.",
      "Field lines point <b>away from positive</b> and <b>towards negative</b>. They never cross. Closer lines mean a stronger field.",
      "When two identical spheres touch, they share the total charge equally: each gets (Q₁ + Q₂) ÷ 2.",
      "Net force or field: add vectors on a line with signs. At 90° use Pythagoras.",
    ],
    defs: [
      ["Coulomb's law", "The magnitude of the electrostatic force exerted by one point charge (Q₁) on another point charge (Q₂) is directly proportional to the product of the magnitudes of the charges and inversely proportional to the square of the distance (r) between them."],
      ["Electric field", "A region of space in which an electric charge experiences a force."],
      ["Electric field at a point", "The (electrostatic) force experienced per unit positive charge placed at that point."],
    ],
    formulas: [
      { label: "Coulomb's law", f: `F = ${fr("kQ₁Q₂", "r²")}`, sheet: true },
      { label: "Field strength", f: `E = ${fr("F", "q")} · E = ${fr("kQ", "r²")}`, sheet: true },
      { label: "Number of electrons", f: `n = ${fr("Q", "e")}, e = 1,6 × 10⁻¹⁹ C`, sheet: true },
      { label: "Constant", f: "k = 9,0 × 10⁹ N·m²·C⁻²", sheet: true },
    ],
    method: [
      "Convert charges to C and distances to m.",
      "Write the formula, substitute magnitudes, calculate.",
      "Give the direction: towards or away from the other charge (or left/right).",
      "Several charges: find each force separately, then add them as vectors.",
    ],
    examples: [
      {
        q: "Charges of +2 µC and −3 µC are 0,3 m apart. Find the force between them.",
        lines: [
          `F = ${fr("kQ₁Q₂", "r²")} ${tk}`,
          `F = ${fr("(9 × 10⁹)(2 × 10⁻⁶)(3 × 10⁻⁶)", "(0,3)²")} ${tk}`,
          `F = 0,6 N, attraction ${tk}`,
        ],
      },
      {
        q: "Find the electric field 0,2 m from a +4 µC charge.",
        lines: [`E = ${fr("kQ", "r²")} = ${fr("(9 × 10⁹)(4 × 10⁻⁶)", "(0,2)²")} ${tk}${tk}`, `E = 9 × 10⁵ N·C⁻¹ away from the charge ${tk}`],
      },
    ],
    mistakes: [
      "Forgetting to square r.",
      "Not converting µC or nC.",
      "Putting negative signs into the formula.",
      "Leaving out the direction of a force or field.",
    ],
    practice: [
      { q: "Identical spheres with +6 µC and −2 µC touch and separate. Charge on each? How many electrons moved?", a: "Each +2 µC. The first sphere changed by 4 µC: n = 4 × 10⁻⁶ ÷ 1,6 × 10⁻¹⁹ = 2,5 × 10¹³ electrons" },
      { q: "The distance between two charges is halved. What happens to the force?", a: "It becomes 4 times bigger (inverse square)" },
      { q: "Electric field 0,5 m from a −5 nC charge?", a: "E = (9 × 10⁹)(5 × 10⁻⁹) ÷ 0,5² = 180 N·C⁻¹ towards the charge" },
      { q: "Define an electric field.", a: "A region of space in which an electric charge experiences a force." },
    ],
    yt: "grade 12 electrostatics coulomb's law exam question",
  },

  {
    id: "p-circuits",
    subj: "phys",
    paper: 1,
    name: "Electric circuits",
    marks: "≈ 15–20",
    where: "Paper 1 · usually Question 8 or 9",
    level: "core",
    hook: "Series and parallel rules plus emf = I(R + r). Questions follow the same steps every time.",
    videos: [
      V("vOrcC7eMAIo", "Electric circuits Internal resistance Intro: PHYSICS grade 11 and 12", "What emf and internal resistance mean."),
      V("a-tALL135yw", "Grade 11 and 12 Electricity Exam with Internal Resistance Part 1", "A full exam question.", "exam"),
      V("RrXkJdV_6-4", "Grade 12 Electric Circuits | Internal Resistance Graphs", "The V vs I graph question."),
    ],
    ideas: [
      "<b>Series</b>: same current everywhere; voltages add up.",
      "<b>Parallel</b>: same voltage across each branch; currents add up.",
      "Adding a resistor in <b>parallel</b> lowers the total resistance → more current → more “lost volts” (Ir) → the terminal voltage drops.",
      "<b>Emf</b> is the battery voltage with no current. <b>Terminal voltage</b> is what the voltmeter reads when current flows.",
      "Electricity cost: kW × hours × price per kWh.",
    ],
    defs: [
      ["Ohm's law", "The potential difference across a conductor is directly proportional to the current in the conductor at constant temperature."],
      ["Emf", "The maximum energy provided (work done) by a battery per coulomb (unit charge) passing through it."],
      ["Internal resistance", "The resistance within a battery."],
      ["Power", "The rate at which electrical energy is converted in an electric circuit (rate at which work is done)."],
      ["Ohmic conductor", "A conductor that obeys Ohm's law."],
    ],
    formulas: [
      { label: "Resistance", f: `R = ${fr("V", "I")}`, sheet: true },
      { label: "Series / parallel", f: `R<sub>s</sub> = R₁ + R₂ + … · ${fr("1", "R<sub>p</sub>")} = ${fr("1", "R₁")} + ${fr("1", "R₂")} + …`, sheet: true },
      { label: "Emf", f: "ε = I(R + r) · V<sub>terminal</sub> = ε − Ir", sheet: true },
      { label: "Charge", f: "q = IΔt", sheet: true },
      { label: "Power & energy", f: `P = VI = I²R = ${fr("V²", "R")} · W = VIΔt`, sheet: true },
    ],
    method: [
      "Find the total external resistance: parallel parts first, then add the series parts.",
      "Use ε = I(R + r) to find the total current.",
      "Voltage across a parallel section = I × R<sub>parallel</sub>. Then split the current: I = V ÷ R for each branch.",
      "Internal resistance: r = (ε − V<sub>terminal</sub>) ÷ I.",
    ],
    examples: [
      {
        q: "A battery (emf 12 V, internal resistance 1 Ω) is connected to a 4 Ω resistor in series with a parallel pair of 6 Ω and 3 Ω. Find the current and the terminal voltage.",
        lines: [
          `R<sub>p</sub> = ${fr("6 × 3", "6 + 3")} = 2 Ω ${tk}`,
          `R<sub>ext</sub> = 4 + 2 = 6 Ω ${tk}`,
          `ε = I(R + r): 12 = I(6 + 1) ${tk}`,
          `I = 1,71 A ${tk}`,
          `V<sub>terminal</sub> = IR = 1,71 × 6 = 10,29 V ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Ignoring internal resistance.",
      "Mixing up emf and terminal voltage.",
      "Adding parallel resistors as if they were in series.",
      "Using the total voltage for a resistor that only has part of it.",
    ],
    practice: [
      { q: "Two 6 Ω resistors in parallel? In series?", a: "Parallel: 3 Ω. Series: 12 Ω" },
      { q: "Emf 9 V. The voltmeter reads 8 V when the current is 0,5 A. Internal resistance?", a: "r = (9 − 8) ÷ 0,5 = 2 Ω" },
      { q: "A 2 000 W kettle runs for 30 minutes at R2,50 per kWh. Cost?", a: "2 kW × 0,5 h = 1 kWh → R2,50" },
      { q: "A resistor is added in parallel. What happens to the terminal voltage? Why?", a: "It decreases. Total resistance drops, current rises, so the lost volts (Ir) increase." },
    ],
    yt: "grade 12 electric circuits internal resistance exam question",
  },

  {
    id: "p-electrodynamics",
    subj: "phys",
    paper: 1,
    name: "Electrodynamics",
    marks: "≈ 10",
    where: "Paper 1 · usually Question 9 or 10",
    level: "core",
    hook: "Mostly theory: motor vs generator, slip rings vs commutator, and the rms formulas. Short questions with quick marks.",
    videos: [
      V("cwsqPceR9L4", "Electrodynamics Generators Introduction Grade 12 Physics", "How generators work."),
      V("g-9GARYLfKQ", "Electrodynamics Motors SUMMARY Grade 12 Physics", "Motors in one summary."),
      V("K54gEqCjpRk", "Grade 12 Electrodynamics AC Calculations: EXAM PRACTICE RMS", "V<sub>rms</sub>, I<sub>rms</sub> and P<sub>ave</sub> calculations.", "exam"),
    ],
    ideas: [
      "<b>Generator</b>: mechanical energy → electrical energy. <b>Motor</b>: electrical energy → mechanical energy.",
      "<b>AC generator</b> uses <b>slip rings</b>. <b>DC generator</b> uses a <b>split-ring commutator</b>.",
      "In a DC motor, the split-ring commutator reverses the current every half turn so the coil keeps turning the same way.",
      "More emf from a generator: more turns on the coil, stronger magnets, or rotate faster.",
      "Household AC is quoted as an rms value. Use rms values in power calculations.",
    ],
    defs: [
      ["Faraday's law of electromagnetic induction", "The emf induced is directly proportional to the rate of change of magnetic flux (flux linkage)."],
      ["Rms value of AC voltage", "The DC potential difference that dissipates the same amount of energy as the AC potential difference."],
    ],
    formulas: [
      { label: "Rms voltage", f: `V<sub>rms</sub> = ${fr("V<sub>max</sub>", rt("2"))}`, sheet: true },
      { label: "Rms current", f: `I<sub>rms</sub> = ${fr("I<sub>max</sub>", rt("2"))}`, sheet: true },
      { label: "Average power", f: `P<sub>ave</sub> = V<sub>rms</sub>I<sub>rms</sub> = I<sub>rms</sub>²R = ${fr("V<sub>rms</sub>²", "R")}`, sheet: true },
    ],
    method: [
      "Theory questions: name the energy conversion or the part (slip rings / commutator / brushes).",
      "Direction questions: use the hand rule your teacher taught you and state it.",
      "Calculations: convert peak to rms first, then use P<sub>ave</sub> = V<sub>rms</sub>I<sub>rms</sub>.",
    ],
    examples: [
      {
        q: "A kettle is rated 2 000 W at 220 V (rms). Find I<sub>rms</sub>, the resistance and the peak current.",
        lines: [
          `P<sub>ave</sub> = V<sub>rms</sub>I<sub>rms</sub>: 2 000 = 220 I<sub>rms</sub> ${tk}`,
          `I<sub>rms</sub> = 9,09 A ${tk}`,
          `R = ${fr("V²", "P")} = ${fr("220²", "2 000")} = 24,2 Ω ${tk}`,
          `I<sub>max</sub> = 9,09 × ${rt("2")} = 12,86 A ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Using peak values in P = VI.",
      "Mixing up slip rings (AC) and the split-ring commutator (DC).",
      "Getting the energy conversion backwards for motors and generators.",
    ],
    practice: [
      { q: "Energy conversion in a generator?", a: "Mechanical energy to electrical energy" },
      { q: "Which part makes a generator AC rather than DC?", a: "Slip rings (a DC generator has a split-ring commutator)" },
      { q: "I<sub>max</sub> = 5 A. I<sub>rms</sub>?", a: "5 ÷ √2 = 3,54 A" },
      { q: "Give two ways to increase the emf of a generator.", a: "Any two: more turns, stronger magnets, faster rotation" },
      { q: "V<sub>max</sub> = 340 V. V<sub>rms</sub>?", a: "340 ÷ √2 = 240,42 V" },
    ],
    yt: "grade 12 electrodynamics motors generators exam question",
  },

  {
    id: "p-photoelectric",
    subj: "phys",
    paper: 1,
    name: "Photoelectric effect",
    marks: "≈ 10",
    where: "Paper 1 · the last question",
    level: "gold",
    hook: "Three definitions and one equation, E = W₀ + E<sub>k</sub>. It's the last question, so make sure you reach it.",
    videos: [
      V("YGlPk4ubn4Y", "Photoelectric Effect | Grade 12 Physical Sciences", "The whole topic, short."),
      V("IHo22w2SG9A", "Threshold Frequency and Work Function Grade 12 Photoelectric Effect", "When electrons are and aren't released."),
      V("ncebHDn94jk", "Photoelectric Effect Revision (NSC Physical Sciences 2019)", "An NSC exam question.", "exam"),
    ],
    ideas: [
      "Light is made of packets of energy called <b>photons</b>. Each has energy E = hf.",
      "An electron escapes only if the photon energy is at least the <b>work function</b> W₀. Extra energy becomes the electron's kinetic energy.",
      "<b>Brighter light</b> (more intensity) → more photons → more electrons → bigger current. The kinetic energy does <b>not</b> change.",
      "<b>Higher frequency</b> light → more kinetic energy per electron.",
      "The photoelectric effect shows the <b>particle nature</b> of light.",
      "Emission spectra: bright lines from excited atoms. Absorption spectra: dark lines. Each element has its own line pattern.",
    ],
    defs: [
      ["Photoelectric effect", "The process whereby electrons are ejected from a metal surface when light of suitable frequency is incident on that surface."],
      ["Threshold frequency (f₀)", "The minimum frequency of light needed to emit electrons from a certain metal surface."],
      ["Work function (W₀)", "The minimum energy that an electron in the metal needs to be emitted from the metal surface."],
    ],
    formulas: [
      { label: "Photon energy", f: `E = hf = ${fr("hc", "λ")}`, sheet: true },
      { label: "Photoelectric equation", f: "E = W₀ + E<sub>k(max)</sub> · hf = hf₀ + ½mv²<sub>max</sub>", sheet: true },
      { label: "Constants", f: "h = 6,63 × 10⁻³⁴ J·s · c = 3,0 × 10⁸ m·s⁻¹ · m<sub>e</sub> = 9,11 × 10⁻³¹ kg", sheet: true },
    ],
    method: [
      "Convert wavelength in nm: × 10⁻⁹ m.",
      "Photon energy: E = hc/λ or E = hf.",
      "Kinetic energy: E<sub>k</sub> = E − W₀. If E &lt; W₀, no electrons are emitted.",
      "Speed: ½mv² = E<sub>k</sub>, so v = √(2E<sub>k</sub>/m).",
    ],
    examples: [
      {
        q: "Light of wavelength 400 nm shines on a metal with W₀ = 3,5 × 10⁻¹⁹ J. Find the maximum speed of the emitted electrons.",
        lines: [
          `E = ${fr("hc", "λ")} = ${fr("(6,63 × 10⁻³⁴)(3 × 10⁸)", "400 × 10⁻⁹")} = 4,97 × 10⁻¹⁹ J ${tk}${tk}`,
          `E<sub>k</sub> = 4,97 × 10⁻¹⁹ − 3,5 × 10⁻¹⁹ = 1,47 × 10⁻¹⁹ J ${tk}`,
          `½(9,11 × 10⁻³¹)v² = 1,47 × 10⁻¹⁹ ${tk}`,
          `v = 5,69 × 10⁵ m·s⁻¹ ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Not converting nm to m.",
      "Saying brighter light gives electrons more kinetic energy. It gives more electrons.",
      "Mixing up f (frequency of the light) and f₀ (threshold frequency of the metal).",
    ],
    practice: [
      { q: "Energy of a photon with f = 6 × 10¹⁴ Hz?", a: "E = (6,63 × 10⁻³⁴)(6 × 10¹⁴) = 3,98 × 10⁻¹⁹ J" },
      { q: "Threshold frequency of a metal with W₀ = 3,3 × 10⁻¹⁹ J?", a: "f₀ = W₀ ÷ h = 4,98 × 10¹⁴ Hz" },
      { q: "The intensity of the light increases. What happens to the number of electrons and their kinetic energy?", a: "More electrons (bigger current). Kinetic energy stays the same." },
      { q: "Define work function.", a: "The minimum energy that an electron in the metal needs to be emitted from the metal surface." },
    ],
    yt: "grade 12 photoelectric effect exam question",
  },

  // ───────────────────────────── PAPER 2: CHEMISTRY ─────────────────────────────
  {
    id: "c-naming",
    subj: "phys",
    paper: 2,
    name: "Organic naming & structure",
    marks: "≈ 20",
    where: "Paper 2 · usually Question 2",
    level: "gold",
    hook: "Learnable rules, no calculations. If you know the prefixes, suffixes and numbering rule, this is one of the best-scoring questions in Paper 2.",
    videos: [
      V("HzscxkG61R4", "Gr. 12 Organic Chemistry: IUPAC-naming (alkanes)", "Naming starts here: chains and branches."),
      V("vIGB9GyBr6k", "IUPAC Naming Made Easy | Organic Chemistry (Grade 12)", "Prefix + stem + suffix, step by step."),
      V("CwzOdwcTXFQ", "Naming Organic Compounds Grade 12", "Functional groups and more examples."),
    ],
    ideas: [
      "Chain length prefixes: <b>meth</b> 1, <b>eth</b> 2, <b>prop</b> 3, <b>but</b> 4, <b>pent</b> 5, <b>hex</b> 6, <b>hept</b> 7, <b>oct</b> 8.",
      "The suffix tells you the family: -ane, -ene, -yne, -ol, -al, -one, -oic acid, -oate (esters).",
      "Branches: methyl (–CH₃), ethyl (–C₂H₅). Halogens: fluoro, chloro, bromo, iodo.",
      "Every carbon has exactly <b>4 bonds</b>. Use this to check structural formulae.",
      "<b>Esters</b> are named alcohol-part first: ethanol + propanoic acid → <b>ethyl propanoate</b>.",
      "<b>Isomers</b> have the same molecular formula but a different structure.",
    ],
    defs: [
      ["Organic molecules", "Molecules containing carbon atoms."],
      ["Hydrocarbon", "Organic compounds that consist of hydrogen and carbon only."],
      ["Homologous series", "A series of organic compounds that can be described by the same general formula OR in which one member differs from the next with a CH₂ group."],
      ["Functional group", "A bond or an atom or a group of atoms that determine(s) the physical and chemical properties of a group of organic compounds."],
      ["Saturated compounds", "Compounds in which there are no multiple bonds between C atoms in their hydrocarbon chains."],
      ["Unsaturated compounds", "Compounds with one or more multiple bonds between C atoms in their hydrocarbon chains."],
      ["Structural isomer", "Organic molecules with the same molecular formula, but different structural formulae."],
      ["Molecular formula", "A chemical formula that indicates the type of atoms and the correct number of each in a molecule."],
      ["Structural formula", "A structural formula of a compound shows which atoms are attached to which within the molecule. Atoms are represented by their chemical symbols and lines are used to represent ALL the bonds that hold the atoms together."],
      ["Condensed structural formula", "This notation shows the way in which atoms are bonded together in the molecule, but DOES NOT SHOW ALL bond lines."],
    ],
    formulas: [
      { label: "Alkanes", f: "CₙH₂ₙ₊₂ · single bonds · -ane", sheet: false },
      { label: "Alkenes", f: "CₙH₂ₙ · C=C · -ene", sheet: false },
      { label: "Alkynes", f: "CₙH₂ₙ₋₂ · C≡C · -yne", sheet: false },
      { label: "Families", f: "alcohol –OH (-ol) · aldehyde –CHO (-al) · ketone C=O in the chain (-one) · carboxylic acid –COOH (-oic acid) · ester –COO– (-yl -oate) · haloalkane (halo-)", sheet: false },
    ],
    method: [
      "Find the <b>longest continuous chain</b> that contains the functional group. Chains can bend on paper.",
      "Number the chain from the end <b>closest to the functional group</b> (or closest to the first branch for alkanes).",
      "Name and number the branches, in alphabetical order. Use di-, tri- for repeats: 2,2-dimethyl.",
      "Put it together: branches + stem + position of functional group + suffix. E.g. 4-methylpentan-2-ol.",
      "Punctuation: commas between numbers, hyphens between numbers and letters.",
    ],
    examples: [
      {
        q: "Name: CH₃CH(CH₃)CH₂CH₃",
        lines: [`Longest chain: 4 carbons (butane) ${tk}`, `Methyl branch on carbon 2 ${tk}`, `2-methylbutane ${tk}`],
      },
      {
        q: "Name: CH₃CH₂CH(OH)CH₃",
        lines: [`4 carbons, alcohol on carbon 2 ${tk}`, `butan-2-ol ${tk}`],
      },
      {
        q: "Name the ester made from ethanol and ethanoic acid.",
        lines: [`Alcohol part: ethyl. Acid part: ethanoate ${tk}`, `ethyl ethanoate ${tk}`],
      },
    ],
    mistakes: [
      "Not finding the longest chain because it bends.",
      "Numbering from the wrong end.",
      "Missing commas and hyphens: 2,2-dimethylpropane, not 22dimethyl propane.",
      "Structural formulae with carbons that don't have 4 bonds, or missing H atoms.",
      "Naming esters acid-part first.",
    ],
    practice: [
      { q: "Name CH₃CH₂CH₂OH", a: "propan-1-ol" },
      { q: "Name CH₂=CHCH₂CH₃", a: "but-1-ene" },
      { q: "Which homologous series does propanone belong to?", a: "Ketones (functional group: carbonyl C=O in the chain)" },
      { q: "Molecular formula of pentane?", a: "C₅H₁₂" },
      { q: "Ester formed from methanol and ethanoic acid?", a: "methyl ethanoate" },
      { q: "Is C₃H₆ saturated or unsaturated?", a: "Unsaturated. It is an alkene (propene), CₙH₂ₙ" },
    ],
    guide: { label: "DBE Mind the Gap study guides (Physical Sciences Part 2: Chemistry)", url: "https://www.education.gov.za/Curriculum/LearningandTeachingSupportMaterials(LTSM)/MindtheGapStudyGuides.aspx" },
    yt: "grade 12 organic chemistry IUPAC naming exam question",
  },

  {
    id: "c-properties",
    subj: "phys",
    paper: 2,
    name: "Organic physical properties",
    marks: "≈ 10",
    where: "Paper 2 · usually Question 3",
    level: "gold",
    hook: "Almost always a “compare boiling points” question. Learn one three-sentence answer template and use it every time.",
    videos: [
      V("MOIQezxToKc", "Grade 12 Organic Chemistry Physical Properties and Intermolecular Forces PART 1", "Intermolecular forces and boiling points."),
      V("EKPH6aXJHyk", "PHYSICAL PROPERTIES | BOILING POINT, MELTING POINT & VAPOUR PRESSURE | GRADE 12", "Boiling point, melting point and vapour pressure together."),
    ],
    ideas: [
      "<b>Stronger intermolecular forces</b> → higher boiling point, higher melting point, <b>lower</b> vapour pressure.",
      "Three kinds of intermolecular force: <b>London forces</b> (every molecule), <b>dipole–dipole</b> (aldehydes, ketones, esters, haloalkanes), <b>hydrogen bonds</b> (alcohols, carboxylic acids).",
      "Similar-sized molecules, boiling point from low to high: alkanes &lt; aldehydes/ketones/esters &lt; alcohols &lt; carboxylic acids.",
      "<b>Longer chain</b> → bigger surface area → stronger London forces → higher boiling point.",
      "<b>More branches</b> → smaller surface area → weaker London forces → lower boiling point.",
      "Boiling breaks the forces <b>between</b> molecules, not the bonds inside them.",
    ],
    defs: [
      ["Boiling point", "The temperature at which the vapour pressure of a substance equals atmospheric pressure."],
      ["Melting point", "The temperature at which the solid and liquid phases of a substance are at equilibrium."],
      ["Vapour pressure", "The pressure exerted by a vapour at equilibrium with its liquid in a closed system."],
    ],
    formulas: [
      { label: "The 3-mark answer template", f: "1. Structure: A has [a longer chain / less branching / hydrogen bonds]. 2. Forces: A has stronger intermolecular forces than B. 3. Energy: more energy is needed to overcome the intermolecular forces in A, so A has the higher boiling point.", sheet: false },
    ],
    method: [
      "Identify the difference between the compounds: chain length, branching, or functional group.",
      "Name the type of intermolecular force in each.",
      "Compare strengths, then connect to energy needed to overcome them.",
      "“Fair test” question: the controlled variable is usually molecular mass or chain length.",
    ],
    examples: [
      {
        q: "Explain why butan-1-ol has a higher boiling point than butanal.",
        lines: [
          `Butan-1-ol has hydrogen bonds (and London forces) between its molecules. Butanal has dipole–dipole forces (and London forces) ${tk}`,
          `Hydrogen bonds are stronger than dipole–dipole forces ${tk}`,
          `More energy is needed to overcome the intermolecular forces in butan-1-ol ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Saying bonds break when a substance boils.",
      "Only describing one compound. Compare both.",
      "Leaving out the energy sentence.",
    ],
    practice: [
      { q: "Higher boiling point: pentane or 2,2-dimethylpropane? Why?", a: "Pentane. It is unbranched, so it has a larger surface area and stronger London forces." },
      { q: "Higher vapour pressure: ethanol or ethanoic acid?", a: "Ethanol. Its intermolecular forces are weaker (one hydrogen-bonding site versus two in the acid)." },
      { q: "Main intermolecular force in propanone?", a: "Dipole–dipole forces" },
      { q: "Define boiling point.", a: "The temperature at which the vapour pressure of a substance equals atmospheric pressure." },
    ],
    yt: "grade 12 organic physical properties boiling point intermolecular forces",
  },

  {
    id: "c-reactions",
    subj: "phys",
    paper: 2,
    name: "Organic reactions",
    marks: "≈ 15",
    where: "Paper 2 · usually Question 4",
    level: "core",
    hook: "Learn the reaction map: what goes in, what comes out, and the conditions. It's a memory topic, so use the flashcards.",
    videos: [
      V("yXabXmtVtww", "[GRADE 12] Addition, Elimination and Substitution Reactions", "The three reaction types side by side."),
      V("mNol3hWwG6k", "Easy Organic Substitution & Esterification Reactions: Grade 12", "Substitution and esterification."),
      V("Y9T-Qnc-Kaw", "Easy Elimination Reactions: Grade 12 Physical Science", "Elimination, including dehydration."),
    ],
    ideas: [
      "<b>Addition</b>: unsaturated (C=C) → saturated. Something adds across the double bond.",
      "<b>Elimination</b>: saturated → unsaturated. A small molecule (H₂O, HX, H₂) is removed.",
      "<b>Substitution</b>: one atom or group is swapped for another. Saturated stays saturated.",
      "<b>Esterification</b>: carboxylic acid + alcohol → ester + water, with concentrated H₂SO₄ as catalyst and heat.",
      "Major product (Markovnikov's rule): the H atom goes to the carbon that already has more H atoms.",
      "Polymers: addition polymers (e.g. polyethene from ethene) and condensation polymers (e.g. polyesters, which release water).",
    ],
    formulas: [
      { label: "Addition", f: "Hydrogenation: alkene + H₂ (Pt/Ni/Pd catalyst) → alkane · Halogenation: alkene + X₂ → dihaloalkane · Hydrohalogenation: alkene + HX → haloalkane · Hydration: alkene + H₂O (H₂SO₄ or H₃PO₄ catalyst) → alcohol", sheet: false },
      { label: "Elimination", f: "Dehydrohalogenation: haloalkane + concentrated strong base (NaOH/KOH) in ethanol, heat → alkene + HX · Dehydration: alcohol + concentrated H₂SO₄ or H₃PO₄, heat → alkene + H₂O · Cracking: long alkane, heat or catalyst → shorter alkane + alkene", sheet: false },
      { label: "Substitution", f: "Hydrolysis: haloalkane + water or dilute NaOH/KOH (aq), mild heat → alcohol · Alcohol + HX → haloalkane + H₂O · Halogenation of alkane: alkane + X₂ in light or heat → haloalkane + HX", sheet: false },
      { label: "Other", f: "Combustion: alkane + O₂ → CO₂ + H₂O · Esterification: acid + alcohol ⇌ ester + H₂O (conc. H₂SO₄, heat)", sheet: false },
    ],
    method: [
      "Compare reactant and product: did it become saturated (addition), unsaturated (elimination) or swap a group (substitution)?",
      "Name the specific reaction (hydration, dehydration, hydrolysis …).",
      "Write the conditions: catalyst, heat, concentrated or dilute, which solvent.",
      "Write balanced equations using structural or condensed formulae as asked.",
    ],
    examples: [
      {
        q: "Bromoethane reacts with concentrated NaOH dissolved in ethanol, with heat. Name the reaction type and the organic product.",
        lines: [`Elimination (dehydrohalogenation) ${tk}`, `Product: ethene ${tk}`],
      },
      {
        q: "Propene reacts with HBr. Give the major product.",
        lines: [`H adds to carbon 1 (it already has more H atoms) ${tk}`, `2-bromopropane ${tk}`],
      },
    ],
    mistakes: [
      "Mixing up the base conditions: concentrated base in ethanol → elimination; dilute aqueous base → substitution.",
      "Forgetting the catalyst (concentrated H₂SO₄) for esterification.",
      "Giving the minor product instead of the major product.",
    ],
    practice: [
      { q: "Ethene + H₂O → ? Reaction type?", a: "Ethanol. Addition (hydration)" },
      { q: "Bromoethane + dilute NaOH(aq) → ?", a: "Ethanol. Substitution (hydrolysis)" },
      { q: "Catalyst for esterification?", a: "Concentrated sulphuric acid (H₂SO₄)" },
      { q: "Butan-2-ol is heated with concentrated H₂SO₄. Reaction type and major product?", a: "Elimination (dehydration). Major product but-2-ene" },
      { q: "Which polymer forms from ethene?", a: "Polyethene (addition polymerisation)" },
    ],
    yt: "grade 12 organic reactions addition elimination substitution",
  },

  {
    id: "c-rates",
    subj: "phys",
    paper: 2,
    name: "Reaction rates & energy",
    marks: "≈ 15",
    where: "Paper 2 · usually Question 5",
    level: "core",
    hook: "Four factors, one explanation template (collision theory), and simple rate and mole calculations.",
    videos: [
      V("n7h5lLjc_ow", "Collision Theory Grade 12 Rate and extent of reaction", "Why the four factors change the rate."),
      V("umnLiQWKyAM", "Rate of Reaction Maxwell-Boltzmann distribution curve Grade 12 Chemistry", "The Maxwell–Boltzmann graph question."),
    ],
    ideas: [
      "Particles react only when they collide with the <b>correct orientation</b> and <b>enough energy</b> (at least the activation energy). These are effective collisions.",
      "<b>Concentration ↑</b>: more particles per unit volume → more effective collisions per unit time.",
      "<b>Temperature ↑</b>: more particles have kinetic energy ≥ activation energy → more effective collisions per unit time.",
      "<b>Surface area ↑</b> (powder instead of lumps): more particles exposed → more effective collisions per unit time.",
      "<b>Catalyst</b>: provides an alternative path with <b>lower activation energy</b>. It does not change ΔH.",
      "Exothermic: ΔH &lt; 0, energy released. Endothermic: ΔH &gt; 0, energy absorbed.",
    ],
    defs: [
      ["Reaction rate", "The change in concentration of reactants or products per unit time."],
      ["Activation energy", "The minimum energy needed for a reaction to take place."],
      ["Catalyst", "A substance that increases the rate of a chemical reaction without itself undergoing a permanent change."],
      ["Activated complex", "The unstable transition state from reactants to products."],
      ["Heat of reaction (ΔH)", "The energy absorbed or released in a chemical reaction."],
      ["Exothermic reaction", "A reaction that releases energy (ΔH &lt; 0)."],
      ["Endothermic reaction", "A reaction that absorbs energy (ΔH &gt; 0)."],
    ],
    formulas: [
      { label: "Rate", f: `rate = ${fr("Δ(amount)", "Δt")}`, sheet: false },
      { label: "Moles", f: `n = ${fr("m", "M")} · c = ${fr("n", "V")} · n = ${fr("V", "V<sub>m</sub>")}`, sheet: true },
      { label: "Molar gas volume", f: "V<sub>m</sub> = 22,4 dm³·mol⁻¹ at STP", sheet: true },
    ],
    method: [
      "“Explain using collision theory”: name the factor → what happens to the particles → more effective collisions per unit time → faster rate.",
      "Graphs of gas volume vs time: steeper = faster. Flat = the reaction has stopped (a reactant is used up).",
      "Same amount of limiting reactant → same final volume of gas, even if the rate differs.",
      "Calculations: convert to moles, use the mole ratio from the balanced equation, convert back.",
    ],
    examples: [
      {
        q: "Explain, using collision theory, why powdered CaCO₃ reacts faster with HCl than lumps.",
        lines: [
          `Powder has a larger surface area ${tk}`,
          `More particles are exposed, so there are more effective collisions per unit time ${tk}`,
          `The reaction rate increases ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Writing “more collisions” instead of “more effective collisions per unit time”.",
      "Saying a catalyst gives the particles more energy. It lowers the activation energy.",
      "Saying a catalyst changes ΔH.",
    ],
    practice: [
      { q: "2 g of magnesium reacts completely in 40 s. Average rate?", a: "2 ÷ 40 = 0,05 g·s⁻¹" },
      { q: "Effect of a catalyst on the heat of reaction?", a: "None. ΔH stays the same." },
      { q: "Explain how a higher temperature increases the rate.", a: "More molecules have kinetic energy ≥ activation energy, so there are more effective collisions per unit time." },
      { q: "Define activation energy.", a: "The minimum energy needed for a reaction to take place." },
    ],
    yt: "grade 12 rates of reaction exam question collision theory",
  },

  {
    id: "c-equilibrium",
    subj: "phys",
    paper: 2,
    name: "Chemical equilibrium",
    marks: "≈ 18",
    where: "Paper 2 · usually Question 6",
    level: "core",
    hook: "Le Chatelier questions follow a pattern, and the Kc calculation uses the same table every time.",
    videos: [
      V("B9vpFq2oJdE", "Le Chatelier's Principle Explained Simply | Chemical Equilibrium (Grade 12)", "How to predict the shift."),
      V("pVPOSnhkiMs", "Equilibrium Constant calculation TABLE METHOD - Easy example (Kc)", "The table method for Kc."),
      V("Z-YkXs_zrPw", "Equilibrium Constant Kc calculation - Exam Question Grade 12", "Kc from an exam question.", "exam"),
    ],
    ideas: [
      "At equilibrium the forward and reverse reactions keep happening at the <b>same rate</b> (dynamic equilibrium).",
      "<b>Le Chatelier</b>: a disturbed system favours the reaction that opposes the change.",
      "Add reactant or remove product → forward reaction favoured.",
      "<b>Increase pressure</b> → the side with fewer moles of gas is favoured.",
      "<b>Increase temperature</b> → the endothermic reaction is favoured.",
      "<b>Kc changes only with temperature.</b> A catalyst speeds up both reactions equally and doesn't change the yield.",
      "Kc uses concentrations of gases and aqueous substances only. Leave out solids and pure liquids.",
    ],
    defs: [
      ["Chemical equilibrium", "A dynamic equilibrium when the rate of the forward reaction equals the rate of the reverse reaction."],
      ["Le Chatelier's principle", "When the equilibrium in a closed system is disturbed, the system will re-instate a new equilibrium by favouring the reaction that will oppose the disturbance."],
    ],
    formulas: [
      { label: "Equilibrium constant", f: `aA + bB ⇌ cC + dD: K<sub>c</sub> = ${fr("[C]<sup>c</sup>[D]<sup>d</sup>", "[A]<sup>a</sup>[B]<sup>b</sup>")}`, sheet: false },
      { label: "Concentration", f: `c = ${fr("n", "V")}`, sheet: true },
      { label: "Kc and temperature", f: "Forward exothermic: T ↑ → Kc ↓ · Forward endothermic: T ↑ → Kc ↑", sheet: false },
    ],
    method: [
      "<b>Le Chatelier</b>: state the change → which reaction is favoured and why → effect on the amount asked for.",
      "<b>Kc table</b>: rows for mole ratio, initial moles, change in moles, equilibrium moles, equilibrium concentration (÷ volume).",
      "Use the substance where you know both the initial and equilibrium amounts to find the change, then use the ratio for the others.",
      "Substitute the concentrations (not moles) into the Kc expression.",
    ],
    examples: [
      {
        q: "2 mol H₂ and 2 mol I₂ are sealed in a 1 dm³ flask: H₂ + I₂ ⇌ 2HI. At equilibrium there are 3 mol HI. Calculate Kc.",
        lines: [
          `Change: HI +3 mol, so H₂ −1,5 mol and I₂ −1,5 mol (ratio 1 : 1 : 2) ${tk}`,
          `Equilibrium: H₂ 0,5; I₂ 0,5; HI 3 mol. Volume 1 dm³, so the same in mol·dm⁻³ ${tk}`,
          `K<sub>c</sub> = ${fr("[HI]²", "[H₂][I₂]")} = ${fr("3²", "(0,5)(0,5)")} ${tk}`,
          `K<sub>c</sub> = 36 ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Putting moles into Kc instead of concentrations.",
      "Including solids or liquid water in Kc.",
      "Saying Kc changes when concentration or pressure changes.",
      "Not saying which reaction (forward or reverse) is favoured.",
    ],
    practice: [
      { q: "Write Kc for N₂ + 3H₂ ⇌ 2NH₃", a: "Kc = [NH₃]² ÷ ([N₂][H₂]³)" },
      { q: "The forward reaction is exothermic. Temperature increases. What happens to Kc?", a: "Kc decreases (the reverse, endothermic reaction is favoured)." },
      { q: "Effect of a catalyst on the yield?", a: "None. Equilibrium is just reached faster." },
      { q: "2SO₂(g) + O₂(g) ⇌ 2SO₃(g). Pressure increases. Which reaction is favoured?", a: "Forward: 3 mol of gas on the left, 2 mol on the right." },
    ],
    yt: "grade 12 chemical equilibrium kc le chatelier exam",
  },

  {
    id: "c-acids",
    subj: "phys",
    paper: 2,
    name: "Acids & bases",
    marks: "≈ 18",
    where: "Paper 2 · usually Question 7",
    level: "core",
    hook: "Definitions, pH calculations and a titration calculation. The titration is always the same four steps.",
    videos: [
      V("X5fhI_EjVY0", "Grade 12 Acids and Bases | pH Calculations", "pH for strong acids and bases."),
      V("lAgdl33AIlM", "ACIDS & BASES | TITRATION CALCULATIONS | GRADE 12", "The titration calculation."),
      V("5FZ_rojJQKY", "Acids and Bases Titrations and pH calculation Past Paper Question", "A past paper question.", "exam"),
    ],
    ideas: [
      "<b>Lowry–Brønsted</b>: an acid donates a proton (H⁺); a base accepts a proton.",
      "<b>Strong</b> means it ionises completely. <b>Concentrated</b> means a lot of solute per volume. They're different ideas.",
      "A <b>conjugate pair</b> differs by one H⁺: HCl / Cl⁻, NH₄⁺ / NH₃.",
      "An <b>ampholyte</b> can act as an acid or a base: H₂O, HCO₃⁻.",
      "pH &lt; 7 acidic, 7 neutral, &gt; 7 basic.",
      "Indicators: strong acid + strong base → bromothymol blue. Strong acid + weak base → methyl orange. Weak acid + strong base → phenolphthalein.",
    ],
    defs: [
      ["Arrhenius acid", "A substance that produces hydrogen ions (H⁺)/hydronium ions (H₃O⁺) when it dissolves in water."],
      ["Arrhenius base", "A substance that produces hydroxide ions (OH⁻) when it dissolves in water."],
      ["Lowry–Brønsted acid", "A proton (H⁺ ion) donor."],
      ["Lowry–Brønsted base", "A proton (H⁺ ion) acceptor."],
      ["Strong acid", "An acid that ionises completely in water to form a high concentration of H₃O⁺ ions."],
      ["Weak acid", "An acid that ionises incompletely in water to form a low concentration of H₃O⁺ ions."],
      ["Strong base", "A base that dissociates completely in water to form a high concentration of OH⁻ ions."],
      ["Weak base", "A base that dissociates/ionises incompletely in water to form a low concentration of OH⁻ ions."],
      ["Ampholyte (amphiprotic substance)", "A substance that can act as either an acid or a base."],
      ["Hydrolysis", "The reaction of a salt with water."],
      ["Equivalence point", "The point at which the acid/base has completely reacted with the base/acid."],
      ["Endpoint", "The point where the indicator changes colour."],
    ],
    formulas: [
      { label: "pH", f: "pH = −log[H₃O⁺]", sheet: true },
      { label: "Water", f: "K<sub>w</sub> = [H₃O⁺][OH⁻] = 1 × 10⁻¹⁴ at 298 K", sheet: true },
      { label: "Titration", f: `${fr("c<sub>a</sub>V<sub>a</sub>", "c<sub>b</sub>V<sub>b</sub>")} = ${fr("n<sub>a</sub>", "n<sub>b</sub>")}`, sheet: true },
      { label: "Moles", f: `n = cV · n = ${fr("m", "M")}`, sheet: true },
    ],
    method: [
      "Write the balanced equation and read off the mole ratio (e.g. H₂SO₄ : NaOH = 1 : 2).",
      "Moles of the known solution: n = cV (convert cm³ ÷ 1 000 to dm³).",
      "Use the ratio to get moles of the unknown.",
      "Concentration of the unknown: c = n ÷ V.",
      "pH of a base: find [OH⁻], then [H₃O⁺] = 10⁻¹⁴ ÷ [OH⁻], then pH = −log[H₃O⁺].",
    ],
    examples: [
      {
        q: "25 cm³ of NaOH is neutralised by 20 cm³ of 0,1 mol·dm⁻³ HCl. Find the concentration of the NaOH.",
        lines: [
          `n(HCl) = cV = 0,1 × 0,020 = 0,002 mol ${tk}`,
          `Ratio 1 : 1, so n(NaOH) = 0,002 mol ${tk}`,
          `c(NaOH) = ${fr("0,002", "0,025")} = 0,08 mol·dm⁻³ ${tk}`,
        ],
      },
      {
        q: "pH of 0,05 mol·dm⁻³ NaOH?",
        lines: [
          `[OH⁻] = 0,05, so [H₃O⁺] = ${fr("1 × 10⁻¹⁴", "0,05")} = 2 × 10⁻¹³ ${tk}`,
          `pH = −log(2 × 10⁻¹³) = 12,70 ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Not converting cm³ to dm³.",
      "Ignoring the mole ratio (H₂SO₄ reacts 1 : 2 with NaOH).",
      "Calculating −log[OH⁻] and calling it the pH.",
      "Confusing strong with concentrated.",
    ],
    practice: [
      { q: "pH of 0,01 mol·dm⁻³ HCl?", a: "pH = −log(0,01) = 2" },
      { q: "Conjugate base of HCl? Conjugate acid of NH₃?", a: "Cl⁻ and NH₄⁺" },
      { q: "20 cm³ of 0,2 mol·dm⁻³ H₂SO₄ is neutralised by NaOH. Moles of NaOH?", a: "n(H₂SO₄) = 0,004 mol; ratio 1 : 2, so n(NaOH) = 0,008 mol" },
      { q: "Indicator for titrating CH₃COOH with NaOH?", a: "Phenolphthalein (weak acid + strong base)" },
      { q: "Is a solution of NH₄Cl acidic or basic?", a: "Acidic: NH₄⁺ + H₂O ⇌ NH₃ + H₃O⁺" },
    ],
    yt: "grade 12 acids and bases titration pH exam question",
  },

  {
    id: "c-electrochem",
    subj: "phys",
    paper: 2,
    name: "Electrochemistry",
    marks: "≈ 20",
    where: "Paper 2 · usually the last two questions",
    level: "core",
    hook: "Two cells, one table. Learn which electrode is which, how to read Table 4, and E°cell = E°cathode − E°anode.",
    videos: [
      V("RRlUImO1Jes", "Electrochemistry Introduction Galvanic vs Electrolytic Cell Grade 12", "The difference between the two cells."),
      V("ODFPFN42WRU", "Galvanic Cell Electrochemistry: How the galvanic cell works | Grade 12", "Anode, cathode, salt bridge and electron flow."),
      V("fBy8RevfytM", "Electrochemistry Grade 12 Past Exam Question Memo", "An exam question with memo.", "exam"),
    ],
    ideas: [
      "<b>OIL RIG</b>: Oxidation Is Loss of electrons, Reduction Is Gain.",
      "<b>AN OX, RED CAT</b>: oxidation at the anode, reduction at the cathode. True for both kinds of cell.",
      "<b>Galvanic cell</b>: a spontaneous reaction makes electricity (chemical → electrical energy).",
      "<b>Electrolytic cell</b>: electricity forces a reaction (electrical → chemical energy). The anode connects to the positive terminal.",
      "The half-reaction with the <b>more positive E°</b> is the reduction (cathode).",
      "Electroplating: the object being plated is the cathode, the plating metal is the anode.",
    ],
    defs: [
      ["Oxidation", "A loss of electrons."],
      ["Reduction", "A gain of electrons."],
      ["Oxidising agent", "A substance that is reduced (gains electrons)."],
      ["Reducing agent", "A substance that is oxidised (loses electrons)."],
      ["Anode", "The electrode where oxidation takes place."],
      ["Cathode", "The electrode where reduction takes place."],
      ["Galvanic cell", "A cell in which chemical energy is converted into electrical energy (a spontaneous reaction)."],
      ["Electrolytic cell", "A cell in which electrical energy is converted into chemical energy (a non-spontaneous reaction)."],
      ["Electrolyte", "A solution/liquid/dissolved substance that conducts electricity through the movement of ions."],
      ["Electrolysis", "The chemical process in which electrical energy is converted to chemical energy, OR the use of electrical energy to produce a chemical change."],
    ],
    formulas: [
      { label: "Cell potential", f: "E°<sub>cell</sub> = E°<sub>cathode</sub> − E°<sub>anode</sub>", sheet: true },
      { label: "Cell notation", f: "Zn | Zn²⁺(1 mol·dm⁻³) || Cu²⁺(1 mol·dm⁻³) | Cu — anode on the left, cathode on the right, || is the salt bridge", sheet: false },
      { label: "Standard conditions", f: "1 mol·dm⁻³, 25 °C (298 K), 101,3 kPa for gases", sheet: false },
    ],
    method: [
      "Find both half-reactions on Table 4A or 4B of the data sheet.",
      "The one with the more positive E° is reduced (cathode). The other is oxidised (anode); write it reversed.",
      "Balance electrons, then add to get the net cell reaction.",
      "E°<sub>cell</sub> = E°<sub>cathode</sub> − E°<sub>anode</sub>. Positive means spontaneous. Never multiply E° values by coefficients.",
      "Electrons flow through the wire from anode to cathode.",
    ],
    examples: [
      {
        q: "A Zn–Cu galvanic cell. E°(Cu²⁺/Cu) = +0,34 V, E°(Zn²⁺/Zn) = −0,76 V. Find E°cell and write the half-reactions.",
        lines: [
          `Cathode (reduction): Cu²⁺ + 2e⁻ → Cu ${tk}`,
          `Anode (oxidation): Zn → Zn²⁺ + 2e⁻ ${tk}`,
          `E°<sub>cell</sub> = 0,34 − (−0,76) ${tk} = 1,10 V ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Calculating anode − cathode instead of cathode − anode.",
      "Multiplying E° by the number of moles in the equation.",
      "Mixing up which electrode connects to the positive terminal in an electrolytic cell.",
      "Forgetting the function of the salt bridge.",
    ],
    practice: [
      { q: "Where does oxidation take place?", a: "At the anode" },
      { q: "E°cell for a Mg–Cu cell? (E° Mg²⁺/Mg = −2,36 V)", a: "0,34 − (−2,36) = 2,70 V" },
      { q: "A spoon is silver-plated. Is the spoon the anode or the cathode?", a: "The cathode" },
      { q: "Function of the salt bridge?", a: "It completes the circuit and keeps the solutions electrically neutral (allows ions to move)." },
      { q: "Reducing agent in Zn + Cu²⁺ → Zn²⁺ + Cu?", a: "Zn (it is oxidised)" },
    ],
    yt: "grade 12 electrochemistry galvanic electrolytic exam question",
  },
];

const TOPICS = [...MATHS_TOPICS, ...PHYS_TOPICS];
const TOPIC = Object.fromEntries(TOPICS.map((t) => [t.id, t]));
