// Maths content. Numbers use the South African exam style: decimal comma,
// semicolons between terms of a sequence, (x; y) for coordinates.
// "✓" (class tk) marks where a DBE memo would award a mark.

const fr = (a, b) => `<span class="fr"><span>${a}</span><span>${b}</span></span>`;
const rt = (x) => `<span class="rt">√<span>${x}</span></span>`;
const tk = '<span class="tk" aria-label="mark">✓</span>';
const V = (id, title, note, kind = "lesson") => ({ id, title, note, kind });

const MATHS_TOPICS = [
  // ───────────────────────────── PAPER 1 ─────────────────────────────
  {
    id: "m-algebra",
    subj: "maths",
    paper: 1,
    name: "Algebra & equations",
    marks: "≈ 25",
    where: "Paper 1 · Question 1, every year",
    level: "gold",
    hook: "Question 1 is the easiest question on Paper 1. Most of these marks are for routine steps you can practise until they're automatic.",
    videos: [
      V("QLe6_aa1o6Q", "How to Solve Quadratic Equations & Inequalities | Grade 12", "Start here. Factorising, the formula and inequalities in one go."),
      V("hT-CfyNVPdg", "Quadratic Inequalities Grade 11 and 12 Maths: Part 1", "Watch if inequalities confuse you. It shows the number-line method."),
      V("7ydr1XUmBok", "Grade 12 Paper 1 June 2019: Equations and Inequalities Q1.1", "A real exam question solved step by step.", "exam"),
    ],
    ideas: [
      "Every equation question is the same move: <b>get everything on one side so it equals 0</b>, then solve.",
      "If it factorises, factorise. If the question says <b>“correct to two decimal places”</b>, it wants the quadratic formula.",
      "Quadratic inequalities: solve like an equation to get the <b>critical values</b>, then decide if the answer is <i>between</i> them or <i>outside</i> them.",
      "Simultaneous equations (one straight line + one curve): make <i>y</i> the subject of the straight-line equation, substitute it into the other one.",
      "Nature of roots is decided by the discriminant Δ = b² − 4ac. You never have to solve the equation.",
    ],
    formulas: [
      { label: "Quadratic formula", f: `x = ${fr("−b ± " + rt("b² − 4ac"), "2a")}`, sheet: true },
      { label: "Discriminant", f: "Δ = b² − 4ac", sheet: false },
      { label: "Nature of roots", f: "Δ &lt; 0: non-real · Δ = 0: equal, real · Δ &gt; 0: unequal, real (rational if Δ is a perfect square)", sheet: false },
      { label: "Exponent laws", f: "a<sup>m</sup> × a<sup>n</sup> = a<sup>m+n</sup> · (a<sup>m</sup>)<sup>n</sup> = a<sup>mn</sup> · a<sup>0</sup> = 1 · a<sup>−n</sup> = " + fr("1", "a<sup>n</sup>"), sheet: false },
    ],
    method: [
      "Write the equation in standard form: ax² + bx + c = 0.",
      "Try to factorise. Set each bracket equal to 0 and solve.",
      "Not factorising, or asked for decimals? Write the formula, substitute a, b and c in brackets, then calculate.",
      "Inequality: factorise, find the critical values, draw a quick number line or parabola sketch and pick the region. If a is negative, multiply by −1 first and flip the sign.",
      "Simultaneous: y = … from the linear equation → substitute → solve the quadratic → find y for <b>each</b> x.",
    ],
    examples: [
      {
        q: "Solve for x: 2x² − 3x − 7 = 0 (correct to two decimal places).",
        lines: [
          `x = ${fr("−(−3) ± " + rt("(−3)² − 4(2)(−7)"), "2(2)")} ${tk}`,
          `x = ${fr("3 ± " + rt("65"), "4")}`,
          `x = 2,77 ${tk} or x = −1,27 ${tk}`,
        ],
      },
      {
        q: "Solve for x: x² − x − 12 ≤ 0",
        lines: [
          `(x − 4)(x + 3) ≤ 0 ${tk}`,
          "Critical values: x = 4 and x = −3",
          `The parabola is below the x-axis between them: −3 ≤ x ≤ 4 ${tk}${tk}`,
        ],
      },
      {
        q: "Solve simultaneously: y = x + 1 and x² + y² = 13",
        lines: [
          `x² + (x + 1)² = 13 ${tk}`,
          "2x² + 2x − 12 = 0  →  x² + x − 6 = 0",
          `(x + 3)(x − 2) = 0 ${tk}`,
          `x = −3, y = −2 ${tk} or x = 2, y = 3 ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Writing only one answer. A quadratic usually has two: write “or” between them.",
      "Dividing both sides by x. You lose the answer x = 0. Factorise x out instead.",
      "Forgetting to flip the inequality sign when you multiply or divide by a negative.",
      "Rounding in the middle of a calculation. Keep the full value on the calculator until the last step.",
      "Finding x in simultaneous equations but not going back to find y.",
    ],
    practice: [
      { q: "Solve: x² + 2x − 15 = 0", a: "(x + 5)(x − 3) = 0, so x = −5 or x = 3" },
      { q: "Solve: 3x² − x − 5 = 0 (two decimal places)", a: `x = ${fr("1 ± " + rt("61"), "6")}, so x = 1,47 or x = −1,14` },
      { q: "Solve: x² − 9 &gt; 0", a: "(x − 3)(x + 3) &gt; 0, so x &lt; −3 or x &gt; 3 (outside the roots)" },
      { q: "Solve simultaneously: y − 2x = 1 and xy = 3", a: "y = 2x + 1 → x(2x + 1) = 3 → 2x² + x − 3 = 0 → (2x + 3)(x − 1) = 0. So x = 1, y = 3 or x = −1,5, y = −2" },
      { q: "Describe the nature of the roots of 2x² − 4x + 5 = 0", a: "Δ = (−4)² − 4(2)(5) = −24. Δ &lt; 0, so the roots are non-real." },
      { q: "Solve: 2<sup>x+1</sup> = 16", a: "16 = 2⁴, so x + 1 = 4 and x = 3" },
    ],
    yt: "grade 12 equations and inequalities past paper question 1",
  },

  {
    id: "m-patterns",
    subj: "maths",
    paper: 1,
    name: "Patterns, sequences & series",
    marks: "≈ 25",
    where: "Paper 1 · usually Questions 2 and 3",
    level: "gold",
    hook: "Almost every mark here comes from choosing the right formula off the information sheet and substituting carefully.",
    videos: [
      V("u55pm2UIzbE", "Quadratic Number Pattern Revision (Grade 12 Mathematics)", "The quadratic pattern method in one short revision."),
      V("uAor910BzQo", "Geometric Series, Sum to infinity & Sigma notation - Grade 12", "Geometric sequences, S∞ and sigma notation."),
      V("NDpLRBK388Y", "NUMBER PATTERNS: QUADRATIC | November 2021 Paper 1 Question 3", "A full November exam question worked out.", "exam"),
    ],
    ideas: [
      "<b>Arithmetic</b>: you add the same number each time (constant difference d).",
      "<b>Geometric</b>: you multiply by the same number each time (constant ratio r).",
      "<b>Quadratic</b>: the <i>second</i> differences are constant. General term Tₙ = an² + bn + c.",
      "Tₙ means “the nth term”. Sₙ means “the sum of the first n terms”. Read which one the question wants.",
      "A geometric series only has a sum to infinity (it converges) when −1 &lt; r &lt; 1.",
      "Sigma: the number of terms = top number − bottom number + 1.",
    ],
    formulas: [
      { label: "Arithmetic term", f: "Tₙ = a + (n − 1)d", sheet: true },
      { label: "Arithmetic sum", f: `Sₙ = ${fr("n", "2")}[2a + (n − 1)d]`, sheet: true },
      { label: "Geometric term", f: "Tₙ = ar<sup>n−1</sup>", sheet: true },
      { label: "Geometric sum", f: `Sₙ = ${fr("a(rⁿ − 1)", "r − 1")}, r ≠ 1`, sheet: true },
      { label: "Sum to infinity", f: `S∞ = ${fr("a", "1 − r")}, −1 &lt; r &lt; 1`, sheet: true },
      { label: "Quadratic pattern", f: "2a = second difference · 3a + b = T₂ − T₁ · a + b + c = T₁", sheet: false },
    ],
    method: [
      "Find the first differences. Constant? Arithmetic. Not constant? Check the ratio T₂ ÷ T₁. Constant ratio? Geometric. Otherwise find second differences: quadratic.",
      "Write the correct formula from the information sheet first. The formula alone can earn a mark.",
      "Substitute what you know (a, d or r, n).",
      "“Which term equals 151?” Set Tₙ = 151 and solve for n. n must be a whole number.",
      "Sigma notation: write out the first three terms by substituting k = 1, 2, 3 to find a and d (or r).",
    ],
    examples: [
      {
        q: "Find the general term of the quadratic pattern 3; 8; 15; 24; …",
        lines: [
          "First differences: 5; 7; 9. Second difference: 2",
          `2a = 2, so a = 1 ${tk}`,
          `3a + b = 5, so b = 2 ${tk}`,
          `a + b + c = 3, so c = 0 ${tk}`,
          `Tₙ = n² + 2n ${tk}`,
        ],
      },
      {
        q: "For 5; 9; 13; … find T₂₀ and S₂₀.",
        lines: [
          "a = 5, d = 4",
          `T₂₀ = 5 + (19)(4) = 81 ${tk}`,
          `S₂₀ = ${fr("20", "2")}[2(5) + (19)(4)] ${tk} = 860 ${tk}`,
        ],
      },
      {
        q: "Find the sum to infinity of 8; 4; 2; …",
        lines: [`a = 8, r = ${fr("1", "2")} ${tk}`, `S∞ = ${fr("8", "1 − ½")} = 16 ${tk}`],
      },
    ],
    mistakes: [
      "Using n instead of (n − 1) in Tₙ = a + (n − 1)d.",
      "Mixing up Tₙ and Sₙ. Underline which one the question asks for.",
      "Counting sigma terms wrong: from k = 3 to k = 10 is 8 terms, not 7.",
      "Forgetting to state the condition −1 &lt; r &lt; 1 when asked why a series converges.",
    ],
    practice: [
      { q: "Find T₁₅ of 2; 7; 12; …", a: "a = 2, d = 5 → T₁₅ = 2 + 14(5) = 72" },
      { q: "Which term of 4; 7; 10; … is 151?", a: "4 + (n − 1)(3) = 151 → n − 1 = 49 → n = 50" },
      { q: "Find Tₙ for 4; 9; 16; 25; …", a: "Second difference 2 → a = 1; 3a + b = 5 → b = 2; a + b + c = 4 → c = 1. Tₙ = n² + 2n + 1" },
      { q: "Calculate Σ (3k + 2) from k = 1 to k = 10", a: "Terms 5; 8; 11; … a = 5, d = 3, n = 10. S₁₀ = 5[10 + 27] = 185" },
      { q: "Find S∞ for 27 + 9 + 3 + …", a: `a = 27, r = ${fr("1", "3")} → S∞ = 27 ÷ ${fr("2", "3")} = 40,5` },
      { q: "A geometric sequence has a = 5 and r = 3. Find S₆.", a: `S₆ = ${fr("5(3⁶ − 1)", "3 − 1")} = 1 820` },
    ],
    yt: "grade 12 sequences and series exam questions",
  },

  {
    id: "m-functions",
    subj: "maths",
    paper: 1,
    name: "Functions & graphs",
    marks: "≈ 35",
    where: "Paper 1 · usually Questions 4 and 5",
    level: "core",
    hook: "Intercepts, turning points, asymptotes and reading off the graph are routine marks. The hard parts are usually the last sub-questions.",
    videos: [
      V("1FHH1qzJ-y4", "Grade 12 - Functions Foundations (hyperbola and exponential: sketching)", "Sketching from zero. Watch this before anything else."),
      V("FR185c_DMj8", "How to find the equation of the parabola, hyperbola and exponential graph", "The “find the equation” questions that come up every year."),
      V("c25fm7-gvT8", "Log & Exponential Functions (Inverses) Grade 12", "Inverses and log graphs, from a past exam question.", "exam"),
      V("u0Cm1cXCStI", "Functions gr 12 Exam Questions", "More exam-style questions once the basics make sense.", "exam"),
    ],
    ideas: [
      "<b>y-intercept</b>: put x = 0. <b>x-intercepts</b>: put y = 0 and solve.",
      "<b>Parabola</b> y = a(x − p)² + q has its turning point at (p; q). a &gt; 0 smiles, a &lt; 0 frowns.",
      "<b>Hyperbola</b> y = a/(x − p) + q has asymptotes x = p and y = q.",
      "<b>Exponential</b> y = a·b<sup>x−p</sup> + q has a horizontal asymptote y = q.",
      "<b>Inverse</b>: swap x and y, then make y the subject. The inverse of y = bˣ is y = log<sub>b</sub>x.",
      "“For which x is f(x) &gt; g(x)?” means: where is the graph of f <i>above</i> the graph of g?",
    ],
    formulas: [
      { label: "Axis of symmetry (parabola)", f: `x = ${fr("−b", "2a")}`, sheet: false },
      { label: "Parabola (turning point form)", f: "y = a(x − p)² + q", sheet: false },
      { label: "Hyperbola", f: `y = ${fr("a", "x − p")} + q`, sheet: false },
      { label: "Exponential", f: "y = a·b<sup>x−p</sup> + q", sheet: false },
      { label: "Hyperbola axes of symmetry", f: "y = (x − p) + q and y = −(x − p) + q", sheet: false },
      { label: "Log definition", f: "y = log<sub>b</sub>x ⇔ x = bʸ", sheet: false },
    ],
    method: [
      "Write down what the equation tells you straight away: turning point or asymptotes.",
      "Find the y-intercept (x = 0) and x-intercepts (y = 0).",
      "Parabola in standard form: turning point x = −b/2a, then substitute to find y.",
      "Sketch: plot intercepts and turning point, draw asymptotes as dotted lines, label every point with coordinates.",
      "Domain and range: parabola range is y ≥ q or y ≤ q; hyperbola x ≠ p, y ≠ q; exponential y &gt; q (if a &gt; 0).",
      "Find the equation: put p and q (from turning point or asymptotes) into the general form, then substitute one more point to find a.",
    ],
    examples: [
      {
        q: "f(x) = x² − 2x − 3. Find the intercepts, turning point and range.",
        lines: [
          `y-intercept: f(0) = −3 ${tk}`,
          `x-intercepts: (x − 3)(x + 1) = 0, so x = 3 or x = −1 ${tk}${tk}`,
          `Turning point: x = ${fr("2", "2")} = 1, f(1) = −4, so (1; −4) ${tk}`,
          `Range: y ≥ −4 ${tk}`,
        ],
      },
      {
        q: `g(x) = ${fr("2", "x − 1")} + 3. Give the asymptotes and intercepts.`,
        lines: [
          `Asymptotes: x = 1 and y = 3 ${tk}${tk}`,
          `y-intercept: g(0) = −2 + 3 = 1 ${tk}`,
          `x-intercept: ${fr("2", "x − 1")} = −3 → x − 1 = −${fr("2", "3")} → x = ${fr("1", "3")} ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Not labelling intercepts, turning points and asymptotes on the sketch. Unlabelled points lose marks.",
      "Drawing asymptotes as solid lines or letting the graph touch them.",
      "Mixing up domain (x-values) and range (y-values).",
      "Including the asymptote value in the range. For y = 2ˣ − 4 the range is y &gt; −4, not y ≥ −4.",
    ],
    practice: [
      { q: "f(x) = −x² + 4. Give the turning point, x-intercepts and range.", a: "Turning point (0; 4). x = ±2. Range y ≤ 4" },
      { q: `g(x) = ${fr("3", "x + 2")} − 1. Give the asymptotes and y-intercept.`, a: "x = −2 and y = −1. y-intercept: 3/2 − 1 = ½" },
      { q: "h(x) = 2ˣ − 4. Asymptote, y-intercept and x-intercept?", a: "y = −4. y-intercept −3. x-intercept: 2ˣ = 4 → x = 2" },
      { q: "A parabola has turning point (2; −9) and passes through (5; 0). Find its equation.", a: "y = a(x − 2)² − 9 → 0 = 9a − 9 → a = 1. y = (x − 2)² − 9" },
      { q: "Write down the inverse of f(x) = 3ˣ.", a: "f⁻¹(x) = log₃x, for x &gt; 0" },
      { q: `Axis of symmetry of y = ${fr("1", "x − 3")} + 2 with a positive gradient?`, a: "y = (x − 3) + 2, so y = x − 1" },
    ],
    yt: "grade 12 functions hyperbola parabola exponential exam",
  },

  {
    id: "m-finance",
    subj: "maths",
    paper: 1,
    name: "Finance, growth & decay",
    marks: "≈ 15",
    where: "Paper 1 · usually Question 6",
    level: "gold",
    hook: "All the formulas are on the information sheet. The marks are for picking the right one and converting the interest rate correctly.",
    videos: [
      V("UHb4fsp2klM", "Financial Mathematics Revision | Compound Interest & Depreciation", "Compound interest and depreciation, exam focused."),
      V("16Hw202Et5o", "Grade 12 Financial Maths Lesson 5 | Present-Value & Future-Value Annuities", "When to use F and when to use P. The key idea of this topic."),
    ],
    ideas: [
      "<b>Saving towards the future</b> (a sinking fund, retirement, monthly deposits): future value F.",
      "<b>Paying off a loan</b> (bond, car loan): present value P. The loan amount is P.",
      "<b>One lump sum growing</b>: A = P(1 + i)ⁿ. <b>Losing value</b> each year (reducing balance): A = P(1 − i)ⁿ.",
      "Always divide the yearly rate by the number of payments per year: 12% p.a. compounded monthly means i = 0,12 ÷ 12.",
      "n is the number of <b>periods</b>, not years: 5 years of monthly payments means n = 60.",
    ],
    formulas: [
      { label: "Simple interest", f: "A = P(1 + ni)", sheet: true },
      { label: "Straight-line depreciation", f: "A = P(1 − ni)", sheet: true },
      { label: "Compound interest", f: "A = P(1 + i)ⁿ", sheet: true },
      { label: "Reducing-balance depreciation", f: "A = P(1 − i)ⁿ", sheet: true },
      { label: "Future value annuity", f: `F = ${fr("x[(1 + i)ⁿ − 1]", "i")}`, sheet: true },
      { label: "Present value annuity", f: `P = ${fr("x[1 − (1 + i)<sup>−n</sup>]", "i")}`, sheet: true },
      { label: "Effective rate", f: `1 + i<sub>eff</sub> = (1 + ${fr("i<sub>nom</sub>", "m")})<sup>m</sup>`, sheet: false },
    ],
    method: [
      "Underline the key words: “p.a.”, “compounded monthly”, “reducing balance”, “monthly payments”.",
      "Decide: lump sum (A = P(1 ± i)ⁿ), savings (F) or loan (P).",
      "Write the formula, then substitute i and n in the correct period.",
      "Type the whole calculation into the calculator in one go. Round only the final answer to 2 decimals (rands and cents).",
      "Finding n? Isolate the bracket, then use logs: n = log(value) ÷ log(1 + i).",
    ],
    examples: [
      {
        q: "R5 000 is invested at 8% p.a. compounded monthly for 3 years. Find the final amount.",
        lines: [
          `A = 5 000(1 + ${fr("0,08", "12")})<sup>36</sup> ${tk}${tk}`,
          `A = R6 351,19 ${tk}`,
        ],
      },
      {
        q: "A R200 000 loan at 12% p.a. compounded monthly is repaid over 20 years. Find the monthly payment.",
        lines: [
          `200 000 = ${fr("x[1 − (1 + 0,01)<sup>−240</sup>]", "0,01")} ${tk}${tk}`,
          `x = R2 202,17 ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Not dividing the rate by 12 for monthly compounding.",
      "Using years for n when payments are monthly.",
      "Rounding i to 0,0067 before calculating. Type 0,08 ÷ 12 into the formula instead.",
      "Using F for a loan or P for a savings plan.",
      "Using (1 + i) for depreciation. Losing value always uses (1 − i).",
    ],
    practice: [
      { q: "A car worth R250 000 depreciates at 15% p.a. on the reducing balance. Its value after 4 years?", a: "A = 250 000(0,85)⁴ = R130 501,56" },
      { q: "Convert 9% p.a. compounded monthly to an effective annual rate.", a: "(1 + 0,09/12)¹² − 1 = 0,0938 → 9,38%" },
      { q: "R1 500 is saved every month for 5 years at 7,5% p.a. compounded monthly. How much is saved?", a: "F = 1 500[(1,00625)⁶⁰ − 1] ÷ 0,00625 = R108 790,66" },
      { q: "How many years for money to double at 6% p.a. compounded annually?", a: "2 = 1,06ⁿ → n = log 2 ÷ log 1,06 = 11,9, so 12 years" },
      { q: "R8 000 at 6% p.a. simple interest for 5 years?", a: "A = 8 000(1 + 5 × 0,06) = R10 400" },
    ],
    yt: "grade 12 financial maths annuities exam question",
  },

  {
    id: "m-calculus",
    subj: "maths",
    paper: 1,
    name: "Differential calculus",
    marks: "≈ 35",
    where: "Paper 1 · usually Questions 7 to 9",
    level: "core",
    hook: "First principles and the derivative rules are the same 10 marks every year. Learn them first; cubic graphs next; optimisation last.",
    videos: [
      V("alUkVWVEP10", "First Principles Calculus Grade 12", "The 5-mark first principles question, done the memo way."),
      V("ckuTYaq_87Y", "First principles grade 12: Practice", "Do these along with the video until it's automatic."),
      V("Kp2LURn8po8", "Grade 12 | Calculus | Sketching a Cubic Function", "Intercepts and turning points of a cubic graph."),
      V("svE_XCm2FcY", "Calculus grade 12 Optimisation: Exam", "Stretch goal. Only after the rest is solid.", "exam"),
    ],
    ideas: [
      "The derivative f′(x) gives the <b>gradient</b> (steepness) of the graph at any point.",
      "<b>First principles</b> is a fixed routine: f(x + h), subtract f(x), divide by h, let h → 0.",
      "<b>Power rule</b>: bring the power down and subtract 1. Rewrite fractions and roots as powers first.",
      "Turning points are where the gradient is 0: solve f′(x) = 0.",
      "Tangent at x = a: gradient m = f′(a), point (a; f(a)), then y − y₁ = m(x − x₁).",
    ],
    formulas: [
      { label: "First principles", f: `f′(x) = lim<sub>h→0</sub> ${fr("f(x + h) − f(x)", "h")}`, sheet: true },
      { label: "Power rule", f: "If f(x) = axⁿ then f′(x) = anx<sup>n−1</sup>", sheet: false },
      { label: "Constant", f: "If f(x) = k then f′(x) = 0", sheet: false },
      { label: "Rewrite before differentiating", f: `${fr("1", "x²")} = x<sup>−2</sup> · ${rt("x")} = x<sup>½</sup>`, sheet: false },
      { label: "Straight line", f: "y − y₁ = m(x − x₁)", sheet: true },
    ],
    method: [
      "<b>First principles:</b> write f(x + h) and expand. Write f′(x) = lim (h→0) [f(x + h) − f(x)] ÷ h. Simplify the top, factor out h, cancel h, then let h → 0. Write “lim” on every line until h is gone.",
      "<b>Rules:</b> multiply out brackets, split fractions over one denominator, write roots and fractions as powers, then differentiate term by term.",
      "<b>Cubic graph:</b> y-intercept (x = 0); x-intercepts by the factor theorem (try f(1), f(−1), f(2)…); turning points from f′(x) = 0; point of inflection from f″(x) = 0.",
      "<b>Tangent:</b> find y at the point, find f′ at the point, substitute into y − y₁ = m(x − x₁).",
    ],
    examples: [
      {
        q: "Determine f′(x) from first principles if f(x) = 2x² − 3.",
        lines: [
          `f(x + h) = 2(x + h)² − 3 = 2x² + 4xh + 2h² − 3 ${tk}`,
          `f(x + h) − f(x) = 4xh + 2h² ${tk}`,
          `f′(x) = lim<sub>h→0</sub> ${fr("4xh + 2h²", "h")} ${tk}`,
          `= lim<sub>h→0</sub> (4x + 2h) ${tk}`,
          `= 4x ${tk}`,
        ],
      },
      {
        q: `Find ${fr("dy", "dx")} if y = 3x⁴ − ${fr("2", "x")} + ${rt("x")}`,
        lines: [
          `y = 3x⁴ − 2x<sup>−1</sup> + x<sup>½</sup> ${tk}`,
          `${fr("dy", "dx")} = 12x³ + 2x<sup>−2</sup> + ½x<sup>−½</sup> ${tk}${tk}${tk}`,
        ],
      },
      {
        q: "f(x) = x³ − 3x + 2. Find the turning points.",
        lines: [
          `f′(x) = 3x² − 3 = 0 ${tk}`,
          `x² = 1, so x = 1 or x = −1 ${tk}`,
          `f(1) = 0 and f(−1) = 4. Turning points (1; 0) and (−1; 4) ${tk}${tk}`,
        ],
      },
    ],
    mistakes: [
      "Dropping “lim h→0” in first principles. The memo takes marks off for notation.",
      "Sign errors when subtracting f(x): put f(x) in brackets.",
      "Differentiating 2/x as 2 instead of rewriting it as 2x⁻¹ first.",
      "Finding the x-value of a turning point and forgetting to find its y-value.",
      "Using the rules when the question says “from first principles”. That scores 0.",
    ],
    practice: [
      { q: "Find f′(x) from first principles for f(x) = x² + 1.", a: "f(x + h) − f(x) = 2xh + h². Divide by h: 2x + h. Let h → 0: f′(x) = 2x" },
      { q: "Differentiate y = 5x³ − 4x + 7", a: "dy/dx = 15x² − 4" },
      { q: "Differentiate y = (x + 2)²", a: "Expand first: x² + 4x + 4, so dy/dx = 2x + 4" },
      { q: `Find D<sub>x</sub>[${fr("x² − 4", "x − 2")}]`, a: "Factorise: (x − 2)(x + 2)/(x − 2) = x + 2, so the derivative is 1" },
      { q: "Equation of the tangent to y = x³ at x = 2", a: "Point (2; 8). dy/dx = 3x² = 12. y − 8 = 12(x − 2), so y = 12x − 16" },
      { q: "Turning points of f(x) = x³ − 12x", a: "f′(x) = 3x² − 12 = 0 → x = ±2. (2; −16) is a minimum and (−2; 16) is a maximum" },
    ],
    yt: "grade 12 calculus first principles cubic graph exam",
  },

  {
    id: "m-probability",
    subj: "maths",
    paper: 1,
    name: "Probability & counting",
    marks: "≈ 15",
    where: "Paper 1 · the last question",
    level: "core",
    hook: "Venn diagrams, tree diagrams and the P(A or B) formula give most of these marks. It's the last question, so leave time for it.",
    videos: [
      V("u4-R3kJWeMQ", "Grade 12 Probability Lesson 5 | Venn diagrams | Mlungisi Nkosi", "Venn diagrams done carefully."),
      V("ut61zNQ92dw", "Mathematics - Grade 12 - The Counting Principle involving Probability", "Arrangements (n!) with probability."),
      V("tqm4ShfH5Zw", "Probability | Venn Diagrams | Final Exam Revision | Mlungisi Nkosi", "Exam revision on the same ideas.", "exam"),
    ],
    ideas: [
      "<b>Mutually exclusive</b>: can't happen together, so P(A and B) = 0.",
      "<b>Independent</b>: one doesn't affect the other, so P(A and B) = P(A) × P(B).",
      "<b>Complementary</b>: P(not A) = 1 − P(A).",
      "Tree diagrams: <b>multiply along</b> the branches, <b>add between</b> branches.",
      "Counting: n different items can be arranged in n! ways. Items that must stay together count as one block.",
    ],
    formulas: [
      { label: "Probability", f: `P(A) = ${fr("n(A)", "n(S)")}`, sheet: true },
      { label: "Addition rule", f: "P(A or B) = P(A) + P(B) − P(A and B)", sheet: true },
      { label: "Independent events", f: "P(A and B) = P(A) × P(B)", sheet: false },
      { label: "Complement", f: "P(not A) = 1 − P(A)", sheet: false },
      { label: "Arrangements with repeats", f: `${fr("n!", "a! b!")} where a, b are the numbers of repeated items`, sheet: false },
    ],
    method: [
      "Venn diagram: fill in the middle (A and B) first, then work outwards. Everything must add up to the total.",
      "Tree diagram: write the probability on every branch. Without replacement, the second set of fractions changes.",
      "Contingency table: complete all the totals first. To test independence, check whether P(A) × P(B) = P(A and B).",
      "Counting: draw one box per position, write how many choices each box has, then multiply.",
    ],
    examples: [
      {
        q: "A and B are independent. P(A) = 0,4 and P(B) = 0,5. Find P(A or B).",
        lines: [
          `P(A and B) = 0,4 × 0,5 = 0,2 ${tk}`,
          `P(A or B) = 0,4 + 0,5 − 0,2 ${tk} = 0,7 ${tk}`,
        ],
      },
      {
        q: "The letters of MATHS are arranged randomly. Find the probability that M is first.",
        lines: [`All arrangements: 5! = 120 ${tk}`, `M first: 4! = 24 ${tk}`, `P = ${fr("24", "120")} = ${fr("1", "5")} ${tk}`],
      },
    ],
    mistakes: [
      "Adding when you should multiply (and the other way round).",
      "Forgetting to subtract P(A and B) in the addition rule.",
      "Without replacement: keeping the same denominator on the second draw.",
      "Codes where digits may repeat: each position has all 10 digits, so 10 × 10 × 10 × 10.",
    ],
    practice: [
      { q: "P(A) = 0,3 and P(B) = 0,6 are mutually exclusive. P(A or B)?", a: "0,3 + 0,6 − 0 = 0,9" },
      { q: "Same values but independent. P(A and B) and P(A or B)?", a: "P(A and B) = 0,18. P(A or B) = 0,3 + 0,6 − 0,18 = 0,72" },
      { q: "How many 4-digit codes can be made from 0–9 if digits may repeat? If they may not?", a: "10⁴ = 10 000. Without repeats: 10 × 9 × 8 × 7 = 5 040" },
      { q: "How many ways to arrange the letters of SCIENCE?", a: "7 letters with C twice and E twice: 7! ÷ (2! × 2!) = 1 260" },
      { q: "A bag has 3 red and 2 blue balls. Two are taken without replacement. P(both red)?", a: "3/5 × 2/4 = 3/10" },
    ],
    yt: "grade 12 probability venn diagram tree diagram exam",
  },

  // ───────────────────────────── PAPER 2 ─────────────────────────────
  {
    id: "m-stats",
    subj: "maths",
    paper: 2,
    name: "Statistics",
    marks: "≈ 20",
    where: "Paper 2 · Questions 1 and 2, every year",
    level: "gold",
    hook: "The first two questions of Paper 2. Your calculator does most of the work: learn the button steps and these are the easiest marks on the paper.",
    videos: [
      V("UrSDjijziMc", "Mean and Standard Deviation on Calculator | Casio fx-82AU PLUS", "Same buttons as the fx-82ZA PLUS. Do it with your calculator in hand.", "calc"),
      V("gp-9iiIsxUE", "Find the regression equation using a Casio calculator", "Getting a, b and r for the regression line.", "calc"),
      V("4YdKyRVmISk", "Grade 12 Statistics: Regression and Correlation", "What the regression line means and how to draw it."),
    ],
    ideas: [
      "<b>Mean</b> = average. <b>Median</b> = middle value when sorted. <b>Mode</b> = most common.",
      "<b>Five-number summary</b>: minimum, Q1, median, Q3, maximum. It is exactly what a box-and-whisker plot shows.",
      "<b>Standard deviation</b> (σ) measures spread around the mean. Get it from the calculator.",
      "Data within one standard deviation of the mean lies between x̄ − σ and x̄ + σ.",
      "<b>Regression line</b> ŷ = a + bx: get a and b from the calculator, then substitute to predict.",
      "<b>Correlation coefficient r</b>: close to 1 or −1 is strong, close to 0 is weak. The sign gives the direction.",
    ],
    formulas: [
      { label: "Mean", f: `x̄ = ${fr("Σx", "n")}`, sheet: true },
      { label: "Variance", f: `σ² = ${fr("Σ(xᵢ − x̄)²", "n")}`, sheet: true },
      { label: "Regression line", f: "ŷ = a + bx", sheet: true },
      { label: "Interquartile range", f: "IQR = Q3 − Q1", sheet: false },
      { label: "Outliers", f: "below Q1 − 1,5 × IQR or above Q3 + 1,5 × IQR", sheet: false },
    ],
    calc: [
      "<b>Casio fx-82ZA PLUS / fx-991ZA PLUS</b> (menu layout of most school calculators):",
      "Mean and standard deviation: MODE → 2 (STAT) → 1 (1-VAR). Type each value, press =. Press AC. Then SHIFT 1 → Var → x̄ for the mean, or σx for the standard deviation.",
      "Regression: MODE → 2 (STAT) → 2 (A+BX). Type x values in the X column and y values in the Y column. AC. SHIFT 1 → Reg → A, B or r.",
      "<b>ClassWiz (fx-82ZA PLUS II / fx-991ZA PLUS II)</b>: MENU → Statistics → 1-Variable or y=a+bx. Enter data, then OPTN → Calc to see every value.",
      "Always use <b>σx</b> (population standard deviation), not sx.",
    ],
    method: [
      "Sort the data from smallest to largest before finding the median or quartiles.",
      "Enter the data into the calculator and read x̄ and σ. Write your answers to 2 decimals.",
      "Box-and-whisker: draw a number line to scale, mark the five-number summary, draw the box from Q1 to Q3 with a line at the median.",
      "Skewness: mean &gt; median means skewed right (positively). Mean &lt; median means skewed left (negatively).",
      "Regression: write the equation as ŷ = a + bx with a and b to 2 decimals, then substitute the given x to predict.",
    ],
    examples: [
      {
        q: "Data: 4; 7; 8; 10; 11; 13; 16. Find the mean, the standard deviation and the five-number summary.",
        lines: [
          `Mean x̄ = ${fr("69", "7")} = 9,86 ${tk}`,
          `σ = 3,68 (calculator) ${tk}`,
          `Minimum 4; Q1 = 7; median = 10; Q3 = 13; maximum 16 ${tk}${tk}`,
        ],
      },
    ],
    mistakes: [
      "Using sx instead of σx on the calculator.",
      "Forgetting to clear old data. Re-enter STAT mode to start fresh.",
      "Finding the median of unsorted data.",
      "Describing correlation with only “positive” or “strong”. Say both, for example “strong positive”.",
      "Calculator left in the wrong mode for the next question. Check the screen.",
    ],
    practice: [
      { q: "Find the mean of 12; 15; 18; 20; 25", a: "90 ÷ 5 = 18" },
      { q: "Five-number summary of 3; 5; 6; 8; 9; 11; 14; 15", a: "Min 3; Q1 = 5,5; median = 8,5; Q3 = 12,5; max 15" },
      { q: "Describe r = −0,93", a: "A very strong negative correlation" },
      { q: "ŷ = 12,5 + 3,2x. Predict y when x = 10.", a: "12,5 + 32 = 44,5" },
      { q: "Q1 = 20 and Q3 = 30. Above what value is a data point an outlier?", a: "IQR = 10. Upper fence: 30 + 15 = 45. Values above 45 are outliers" },
    ],
    yt: "grade 12 statistics casio calculator standard deviation regression",
  },

  {
    id: "m-anageo",
    subj: "maths",
    paper: 2,
    name: "Analytical geometry",
    marks: "≈ 40",
    where: "Paper 2 · usually Questions 3 and 4",
    level: "core",
    hook: "The first sub-questions are distance, midpoint, gradient and equation of a line: straight formula substitution. Collect those marks every time.",
    videos: [
      V("NqED6lOqVjI", "Grade 12 Analytical Geometry | Inclination, Gradient, Distance and Mid Point", "All the basic formulas in one video. Start here."),
      V("4I9OcKET5Ys", "Analytical geometry Lesson 2 | The equation of a circle & tangent to a circle | Mlungisi Nkosi", "Circle equations and tangents."),
      V("2IcDN1Ik-04", "Grade 12 - Analytical Geometry: Circles (exam-type questions)", "Exam-type circle questions.", "exam"),
    ],
    ideas: [
      "Every question here uses a handful of formulas, all on the information sheet.",
      "<b>Parallel</b> lines have equal gradients. <b>Perpendicular</b> lines: m₁ × m₂ = −1.",
      "A <b>tangent</b> to a circle is perpendicular to the radius at the point where it touches.",
      "The gradient is the tan of the angle of inclination: m = tan θ. If m is negative, θ = 180° + tan⁻¹(m).",
      "A circle not in standard form? Complete the square to find the centre and radius.",
    ],
    formulas: [
      { label: "Distance", f: `d = ${rt("(x₂ − x₁)² + (y₂ − y₁)²")}`, sheet: true },
      { label: "Midpoint", f: `M(${fr("x₁ + x₂", "2")}; ${fr("y₁ + y₂", "2")})`, sheet: true },
      { label: "Gradient", f: `m = ${fr("y₂ − y₁", "x₂ − x₁")}`, sheet: true },
      { label: "Straight line", f: "y = mx + c · y − y₁ = m(x − x₁)", sheet: true },
      { label: "Inclination", f: "m = tan θ", sheet: true },
      { label: "Circle", f: "(x − a)² + (y − b)² = r², centre (a; b)", sheet: true },
    ],
    method: [
      "Draw a quick sketch and mark the given points. It stops sign mistakes.",
      "Write the formula, substitute with brackets around negative numbers, simplify.",
      "Equation of a line: find the gradient first, then use y − y₁ = m(x − x₁).",
      "Tangent at a point on a circle: gradient of the radius → negative reciprocal → line equation.",
      "Circle in the form x² + y² + Dx + Ey + F = 0: complete the square for x and for y.",
    ],
    examples: [
      {
        q: "A(−1; 2) and B(3; 4). Find AB, the midpoint of AB, the gradient and the equation of AB.",
        lines: [
          `AB = ${rt("(3 + 1)² + (4 − 2)²")} = ${rt("20")} = 4,47 ${tk}`,
          `M(1; 3) ${tk}`,
          `m = ${fr("4 − 2", "3 + 1")} = ${fr("1", "2")} ${tk}`,
          `y − 2 = ½(x + 1), so y = ½x + 2½ ${tk}`,
        ],
      },
      {
        q: "Find the centre and radius of x² + y² − 6x + 4y − 12 = 0.",
        lines: [
          `(x − 3)² − 9 + (y + 2)² − 4 − 12 = 0 ${tk}`,
          `(x − 3)² + (y + 2)² = 25 ${tk}`,
          `Centre (3; −2), radius 5 ${tk}${tk}`,
        ],
      },
    ],
    mistakes: [
      "Subtracting coordinates in a different order on the top and bottom of the gradient formula.",
      "Forgetting the negative reciprocal for perpendicular lines.",
      "Negative gradient: giving θ = tan⁻¹(m) without adding 180°.",
      "Writing r instead of r² on the right-hand side of the circle equation.",
    ],
    practice: [
      { q: "Distance between (2; 5) and (−4; −3)", a: "√(36 + 64) = √100 = 10" },
      { q: "Gradient and inclination of the line through (1; −2) and (4; 7)", a: "m = 9/3 = 3. θ = tan⁻¹3 = 71,57°" },
      { q: "Equation of the line perpendicular to y = 2x + 1 through (4; 1)", a: "m = −½. y − 1 = −½(x − 4), so y = −½x + 3" },
      { q: "Centre and radius of x² + y² + 4x − 10y + 20 = 0", a: "(x + 2)² + (y − 5)² = 9. Centre (−2; 5), radius 3" },
      { q: "Inclination of a line with gradient −1", a: "180° − 45° = 135°" },
      { q: "Tangent to x² + y² = 25 at (3; 4)", a: "Radius gradient 4/3, so tangent gradient −3/4. y − 4 = −¾(x − 3), so y = −¾x + 6¼" },
    ],
    yt: "grade 12 analytical geometry circle tangent exam",
  },

  {
    id: "m-trig",
    subj: "maths",
    paper: 2,
    name: "Trigonometry",
    marks: "≈ 50",
    where: "Paper 2 · usually Questions 5 to 7",
    level: "core",
    hook: "The biggest topic in Paper 2. Special angles and reduction formulae are pure memory and appear in every paper, so learn them first.",
    videos: [
      V("F7_ywqhTQ38", "Lesson 1: How To Use Reduction Formulae | Grade 12 Trigonometry", "Start here: CAST and reduction."),
      V("0JqDvMpClqU", "Trigonometry Grade 12 Reduction: practice", "Practise reduction until it's quick.", "exam"),
      V("UAaf14YizQw", "General solution grade 12 Trigonometry", "The general-solution method with k ∈ ℤ."),
      V("L68x0ANHrng", "Trig Identities | Double Angles | Exam Question", "How to prove an identity, exam style.", "exam"),
      V("zO2UJ3EVyvs", "Sine Rule, Cosine Rule and Area Rule - Exam Questions", "2D problems with the three triangle rules.", "exam"),
    ],
    ideas: [
      "<b>CAST</b>: in quadrant 1 All ratios are positive, in quadrant 2 Sin, in quadrant 3 Tan, in quadrant 4 Cos.",
      "<b>Reduction</b> turns any angle into an acute angle: 180° − θ, 180° + θ, 360° − θ keep the same ratio, only the sign changes. 90° ± θ swaps sin and cos.",
      "<b>Special angles</b> (30°, 45°, 60°) must be answered without a calculator. Learn the triangle values by heart.",
      "<b>Identities</b>: tan θ = sin θ/cos θ and sin²θ + cos²θ = 1 are not on the information sheet.",
      "<b>Equations</b>: get one trig ratio alone, find the reference angle, use CAST for the quadrants, add k·360° (or k·180° for tan).",
      "<b>Triangles</b> without a right angle: sine rule, cosine rule and area rule.",
    ],
    formulas: [
      { label: "Special angles", f: `sin 30° = ${fr("1", "2")} · cos 30° = ${fr(rt("3"), "2")} · tan 30° = ${fr("1", rt("3"))} · sin 45° = cos 45° = ${fr("1", rt("2"))} · tan 45° = 1 · sin 60° = ${fr(rt("3"), "2")} · cos 60° = ${fr("1", "2")} · tan 60° = ${rt("3")}`, sheet: false },
      { label: "Reduction (180°)", f: "sin(180° − θ) = sin θ · cos(180° − θ) = −cos θ · tan(180° − θ) = −tan θ · sin(180° + θ) = −sin θ · cos(180° + θ) = −cos θ · tan(180° + θ) = tan θ", sheet: false },
      { label: "Reduction (360° and −θ)", f: "sin(360° − θ) = sin(−θ) = −sin θ · cos(360° − θ) = cos(−θ) = cos θ · tan(360° − θ) = −tan θ", sheet: false },
      { label: "Co-functions", f: "sin(90° − θ) = cos θ · cos(90° − θ) = sin θ · sin(90° + θ) = cos θ · cos(90° + θ) = −sin θ", sheet: false },
      { label: "Identities", f: `tan θ = ${fr("sin θ", "cos θ")} · sin²θ + cos²θ = 1`, sheet: false },
      { label: "Compound angles", f: "sin(α ± β) = sin α cos β ± cos α sin β · cos(α ± β) = cos α cos β ∓ sin α sin β", sheet: true },
      { label: "Double angles", f: "sin 2α = 2 sin α cos α · cos 2α = cos²α − sin²α = 1 − 2sin²α = 2cos²α − 1", sheet: true },
      { label: "Triangle rules", f: `${fr("a", "sin A")} = ${fr("b", "sin B")} · a² = b² + c² − 2bc cos A · Area = ½ab sin C`, sheet: true },
      { label: "General solution", f: "sin θ = k: θ = ref + k·360° or (180° − ref) + k·360° · cos θ = k: θ = ±ref + k·360° · tan θ = k: θ = ref + k·180°, k ∈ ℤ", sheet: false },
    ],
    method: [
      "<b>Set your calculator to DEG.</b> Check it at the start of every paper.",
      "<b>Simplify / evaluate:</b> reduce every angle first, one step per line (each reduction earns a mark), then use special angles.",
      "<b>Prove an identity:</b> start from the more complicated side. Change tan to sin/cos, use sin²θ + cos²θ = 1, spot double angles. Work on one side only, and end with “= RHS”.",
      "<b>Solve an equation:</b> make it one ratio of one angle (e.g. sin x = 0,5), find the reference angle, place it using CAST, write the general solution with k ∈ ℤ.",
      "<b>Triangle problems:</b> sides and opposite angles known → sine rule. Two sides and the angle between them → cosine rule or area rule.",
    ],
    examples: [
      {
        q: "Evaluate without a calculator: (sin 150° · tan 225°) ÷ cos 300°",
        lines: [
          `= (sin 30° · tan 45°) ÷ cos 60° ${tk}${tk}${tk}`,
          `= (½ × 1) ÷ ½ ${tk}`,
          `= 1 ${tk}`,
        ],
      },
      {
        q: "Find the general solution of 2 sin x = 1.",
        lines: [
          `sin x = ½, reference angle 30° ${tk}`,
          `x = 30° + k·360° ${tk} or x = 150° + k·360°, k ∈ ℤ ${tk}`,
        ],
      },
      {
        q: `Prove: ${fr("1 − cos²x", "sin x cos x")} = tan x`,
        lines: [`LHS = ${fr("sin²x", "sin x cos x")} ${tk}`, `= ${fr("sin x", "cos x")} ${tk}`, `= tan x = RHS ${tk}`],
      },
      {
        q: "In △ABC, b = 8, c = 5 and Â = 60°. Find a and the area.",
        lines: [
          `a² = 8² + 5² − 2(8)(5) cos 60° ${tk}`,
          `a² = 49, so a = 7 ${tk}`,
          `Area = ½(8)(5) sin 60° = 17,32 square units ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Calculator in RAD or GRAD mode. Every answer will be wrong.",
      "Forgetting “k ∈ ℤ” in a general solution.",
      "Finding only one of the two solutions for sin or cos.",
      "Putting the negative sign into the reference angle calculation. Use the positive value to get the reference angle.",
      "Working on both sides of an identity at the same time.",
    ],
    practice: [
      { q: "Without a calculator: cos 120°", a: "cos(180° − 60°) = −cos 60° = −½" },
      { q: "Simplify tan(180° + x) · cos(360° − x)", a: "tan x · cos x = (sin x/cos x) · cos x = sin x" },
      { q: "General solution of tan x = 1", a: "x = 45° + k·180°, k ∈ ℤ" },
      { q: "sin θ = 3/5 and θ is obtuse. Find cos θ.", a: "Quadrant 2: y = 3, r = 5, so x = −4. cos θ = −4/5" },
      { q: "Prove: sin 2x ÷ (2 sin x) = cos x", a: "LHS = 2 sin x cos x ÷ 2 sin x = cos x = RHS" },
      { q: "Use sin(45° + 30°) to find sin 75° without a calculator", a: "sin 45° cos 30° + cos 45° sin 30° = (√3 + 1) ÷ (2√2), which equals (√6 + √2)/4" },
      { q: "Period of y = cos 2x? Amplitude of y = 3 sin x?", a: "Period 180°. Amplitude 3" },
    ],
    yt: "grade 12 trigonometry reduction identities general solution exam",
  },

  {
    id: "m-geometry",
    subj: "maths",
    paper: 2,
    name: "Euclidean geometry",
    marks: "≈ 40",
    where: "Paper 2 · usually the last three questions",
    level: "core",
    hook: "Learn the six examinable theorem proofs word for word (often 5–6 marks), and give a reason for every statement. Riders are hard, but each correct statement plus reason earns a mark.",
    videos: [
      V("0ZzlADJa4u0", "Grade 12 Geometry Lesson 3 | Euclidean Geometry: Circle Geometry", "All the Grade 11 circle theorems and what to look for."),
      V("PZ4knzqw8LM", "Gr 12 Maths (Euclidean Geometry | Theorems | Proofs | Reasoning Made Easy)", "How to set out statements and reasons."),
      V("sq8awNWBvT8", "Euclidean Geometry - Proportionality and Similarity (Paper 2)", "The Grade 12 part: proportion and similar triangles."),
      V("iVrVD7GxMvw", "How to prove the proportionality theorem", "One of the six proofs you can be asked to write out."),
      V("EltaHVlbTug", "SIMILARITY THEOREM PROOF GRADE 12", "Another examinable proof."),
    ],
    ideas: [
      "Every line you write needs a <b>statement and a reason</b>. A statement with no reason gets no mark.",
      "Use the <b>accepted reasons</b> (in the Drill section under Geometry reasons). Your own words may not be accepted.",
      "Look for: radii (equal sides, so isosceles triangles), a diameter (90° in the semicircle), tangents (90° to the radius, tan-chord), cyclic quads, parallel lines.",
      "Name angles clearly: use three letters (AB̂C) or the numbered angles on the diagram (B̂₁).",
      "<b>Six proofs are examinable</b>: (1) line from centre ⊥ chord bisects chord; (2) angle at centre = 2 × angle at circumference; (3) opposite angles of a cyclic quad are supplementary; (4) tan-chord theorem; (5) proportionality theorem; (6) equiangular triangles are similar.",
    ],
    formulas: [
      { label: "Proportionality", f: `DE ∥ BC in △ABC ⇒ ${fr("AD", "DB")} = ${fr("AE", "EC")}`, sheet: false },
      { label: "Midpoint theorem", f: "The line joining midpoints of two sides is parallel to the third side and half as long", sheet: false },
      { label: "Similar triangles", f: `△ABC ||| △DEF ⇒ ${fr("AB", "DE")} = ${fr("BC", "EF")} = ${fr("AC", "DF")}`, sheet: false },
    ],
    proofs: [
      {
        name: "Line from centre ⊥ to chord bisects the chord",
        fig: "chord",
        given: "Circle centre O, OM ⊥ AB.",
        rtp: "AM = MB",
        construction: "Join OA and OB.",
        steps: [
          ["In △OMA and △OMB:", ""],
          ["OA = OB", "radii"],
          ["OM = OM", "common"],
          ["OM̂A = OM̂B = 90°", "given"],
          ["△OMA ≡ △OMB", "RHS"],
          ["AM = MB", "≡ △s"],
        ],
      },
      {
        name: "Angle at centre = 2 × angle at circumference",
        fig: "centre",
        given: "Circle centre O, arc AB subtends AÔB at the centre and AĈB at the circle.",
        rtp: "AÔB = 2AĈB",
        construction: "Join CO and extend it to D.",
        steps: [
          ["OA = OC", "radii"],
          ["Â = Ĉ₁", "∠s opp equal sides"],
          ["Ô₁ = Â + Ĉ₁", "ext ∠ of △"],
          ["Ô₁ = 2Ĉ₁", ""],
          ["Similarly Ô₂ = 2Ĉ₂", ""],
          ["AÔB = Ô₁ + Ô₂ = 2(Ĉ₁ + Ĉ₂) = 2AĈB", ""],
        ],
      },
      {
        name: "Opposite angles of a cyclic quadrilateral are supplementary",
        fig: "cyclic",
        given: "Cyclic quadrilateral ABCD in a circle with centre O.",
        rtp: "Â + Ĉ = 180°",
        construction: "Join OB and OD.",
        steps: [
          ["Ô₁ = 2Â", "∠ at centre = 2 × ∠ at circumference"],
          ["Ô₂ = 2Ĉ", "∠ at centre = 2 × ∠ at circumference"],
          ["Ô₁ + Ô₂ = 360°", "∠s around a point"],
          ["2Â + 2Ĉ = 360°", ""],
          ["Â + Ĉ = 180°", ""],
        ],
      },
    ],
    method: [
      "Copy the given facts onto the diagram (mark equal sides, 90° angles, parallel lines).",
      "Before writing, look for isosceles triangles from radii, a diameter, tangents, cyclic quads and parallel lines.",
      "Write one statement per line with its reason in brackets or in a second column.",
      "Stuck on a rider? Still write every angle you can find with its reason. Each correct statement and reason earns marks.",
      "For proportion questions, write the ratio with the theorem name, then substitute the lengths.",
    ],
    examples: [
      {
        q: "O is the centre. AĈB = 35° (at the circumference). Find AÔB.",
        lines: [`AÔB = 70° ${tk} (∠ at centre = 2 × ∠ at circumference) ${tk}`],
      },
      {
        q: "In △ABC, DE ∥ BC with D on AB and E on AC. AD = 4, DB = 6, AE = 5. Find EC.",
        lines: [
          `${fr("AD", "DB")} = ${fr("AE", "EC")} ${tk} (line ∥ one side of △) ${tk}`,
          `${fr("4", "6")} = ${fr("5", "EC")}, so EC = 7,5 ${tk}`,
        ],
      },
    ],
    mistakes: [
      "Writing a statement without a reason.",
      "Assuming something is true because it looks true in the drawing (e.g. assuming a quad is cyclic).",
      "Calling an angle “Â” when there are several angles at A.",
      "Using a theorem's converse the wrong way round (e.g. to prove a quad is cyclic you need a converse reason).",
    ],
    practice: [
      { q: "ABCD is a cyclic quad with Â = 110°. Find Ĉ and give a reason.", a: "Ĉ = 70° (opp ∠s of cyclic quad)" },
      { q: "AB is a diameter and C lies on the circle. AĈB = ?", a: "90° (∠ in semi-circle)" },
      { q: "A tangent at A makes 50° with chord AB. What is the angle in the alternate segment?", a: "50° (tan chord theorem)" },
      { q: "OM ⊥ AB, AB = 10 cm, O is the centre. Find AM.", a: "5 cm (line from centre ⊥ to chord)" },
      { q: "Two tangents from P touch the circle at A and B. What do you know about PA and PB?", a: "PA = PB (tans from common pt)" },
    ],
    guide: { label: "DBE Mind the Gap: Mathematics (has all the theorem proofs with diagrams)", url: "https://www.education.gov.za/Portals/0/Documents/Manuals/MTG%20Math%20Gr%2012%20Web.pdf?ver=2015-02-25-211420-000" },
    yt: "grade 12 euclidean geometry theorem proofs riders",
  },
];
