"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-01 17:08:27.488914
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.core.database

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_calls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('task', sa.String(length=30), nullable=False),
    sa.Column('prompt_name', sa.String(length=60), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=True),
    sa.Column('cached', sa.Boolean(), nullable=False),
    sa.Column('signal_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_calls_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_calls_provider'), ['provider'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=300), nullable=True),
    sa.Column('cooldown_minutes', sa.Integer(), nullable=False),
    sa.Column('last_triggered_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_state', sa.JSON(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('backtests',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('strategy_version', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('data_label', sa.String(length=120), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('engine_version', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtests_strategy'), ['strategy'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtests_symbol'), ['symbol'], unique=False)

    op.create_table('briefings',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('session', sa.String(length=20), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('is_ai', sa.Boolean(), nullable=False),
    sa.Column('is_demo_data', sa.Boolean(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('briefings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_briefings_session'), ['session'], unique=False)

    op.create_table('economic_events',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('event', sa.String(length=200), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('country', sa.String(length=60), nullable=False),
    sa.Column('scheduled_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('impact', sa.String(length=8), nullable=False),
    sa.Column('previous', sa.String(length=40), nullable=True),
    sa.Column('forecast', sa.String(length=40), nullable=True),
    sa.Column('actual', sa.String(length=40), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('fetched_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_event')
    )
    with op.batch_alter_table('economic_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_economic_events_currency'), ['currency'], unique=False)
        batch_op.create_index(batch_op.f('ix_economic_events_impact'), ['impact'], unique=False)
        batch_op.create_index(batch_op.f('ix_economic_events_scheduled_at'), ['scheduled_at'], unique=False)

    op.create_table('historical_setups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('ts', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('regime', sa.String(length=24), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=False),
    sa.Column('entry', sa.Float(), nullable=False),
    sa.Column('stop', sa.Float(), nullable=False),
    sa.Column('effective_rr', sa.Float(), nullable=False),
    sa.Column('outcome_status', sa.String(length=20), nullable=False),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('bars_held', sa.Integer(), nullable=False),
    sa.Column('mfe_r', sa.Float(), nullable=True),
    sa.Column('mae_r', sa.Float(), nullable=True),
    sa.Column('tp1_before_sl', sa.Boolean(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('signal_engine_version', sa.String(length=16), nullable=False),
    sa.Column('signal_id', sa.String(length=40), nullable=True),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historical_setups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historical_setups_outcome_status'), ['outcome_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_historical_setups_ts'), ['ts'], unique=False)
        batch_op.create_index('ix_setup_lookup', ['symbol', 'timeframe', 'direction', 'is_demo'], unique=False)

    op.create_table('market_assets',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('session', sa.String(length=10), nullable=False),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    with op.batch_alter_table('market_assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_assets_asset_class'), ['asset_class'], unique=False)

    op.create_table('market_candles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('ts', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('batch', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'symbol', 'timeframe', 'ts', name='uq_candle')
    )
    with op.batch_alter_table('market_candles', schema=None) as batch_op:
        batch_op.create_index('ix_candle_lookup', ['symbol', 'timeframe', 'ts'], unique=False)
        batch_op.create_index(batch_op.f('ix_market_candles_is_demo'), ['is_demo'], unique=False)

    op.create_table('market_features',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('ts', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_features', schema=None) as batch_op:
        batch_op.create_index('ix_feature_lookup', ['symbol', 'timeframe', 'ts'], unique=False)

    op.create_table('market_regimes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('ts', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('regime', sa.String(length=24), nullable=False),
    sa.Column('clarity', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('market_regimes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_market_regimes_regime'), ['regime'], unique=False)
        batch_op.create_index('ix_regime_lookup', ['symbol', 'timeframe', 'ts'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=True),
    sa.Column('first_used_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('uses', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kind', 'provider', 'model', 'version', name='uq_model_version')
    )
    op.create_table('news',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('published_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('symbols', sa.JSON(), nullable=False),
    sa.Column('countries', sa.JSON(), nullable=False),
    sa.Column('sentiment', sa.String(length=12), nullable=True),
    sa.Column('sentiment_source', sa.String(length=40), nullable=True),
    sa.Column('sentiment_rationale', sa.Text(), nullable=True),
    sa.Column('importance', sa.String(length=8), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('data_change_pct', sa.Float(), nullable=True),
    sa.Column('fetched_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_news')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_published_at'), ['published_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('signal_id', sa.String(length=40), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_ts'), ['ts'], unique=False)

    op.create_table('paper_accounts',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('kill_switch', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('bar_time', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('proposed_direction', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('score_long', sa.Float(), nullable=False),
    sa.Column('score_short', sa.Float(), nullable=False),
    sa.Column('regime', sa.String(length=24), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('entry_type', sa.String(length=10), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('entry_zone_low', sa.Float(), nullable=True),
    sa.Column('entry_zone_high', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('invalidation_level', sa.Float(), nullable=True),
    sa.Column('invalidation_text', sa.Text(), nullable=True),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('rr', sa.Float(), nullable=True),
    sa.Column('effective_rr', sa.Float(), nullable=True),
    sa.Column('expires_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('expiry_bars', sa.Integer(), nullable=False),
    sa.Column('supporting', sa.JSON(), nullable=False),
    sa.Column('opposing', sa.JSON(), nullable=False),
    sa.Column('no_trade_reasons', sa.JSON(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('components', sa.JSON(), nullable=False),
    sa.Column('mtf_adjustment', sa.Float(), nullable=False),
    sa.Column('ensemble', sa.JSON(), nullable=True),
    sa.Column('evidence', sa.JSON(), nullable=True),
    sa.Column('ai_summary', sa.JSON(), nullable=True),
    sa.Column('risk_decision', sa.JSON(), nullable=True),
    sa.Column('calibrated_probability', sa.Float(), nullable=True),
    sa.Column('data_mode', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('signal_engine_version', sa.String(length=16), nullable=False),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('risk_engine_version', sa.String(length=16), nullable=True),
    sa.Column('strategy_versions', sa.JSON(), nullable=False),
    sa.Column('prompt_versions', sa.JSON(), nullable=False),
    sa.Column('model_versions', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.create_index('ix_signal_dedupe', ['symbol', 'timeframe', 'bar_time'], unique=False)
        batch_op.create_index('ix_signal_status', ['status'], unique=False)
        batch_op.create_index('ix_signal_symbol_time', ['symbol', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_is_demo'), ['is_demo'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_score'), ['score'], unique=False)
        batch_op.create_index(batch_op.f('ix_signals_timeframe'), ['timeframe'], unique=False)

    op.create_table('strategies',
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('regimes', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('strategy_regime_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=False),
    sa.Column('regime', sa.String(length=24), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('trades', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('sum_r', sa.Float(), nullable=False),
    sa.Column('sum_pnl', sa.Float(), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy', 'regime', 'source', 'is_demo', name='uq_strategy_regime')
    )
    with op.batch_alter_table('strategy_regime_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_regime_stats_strategy'), ['strategy'], unique=False)

    op.create_table('system_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('signal_id', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_system_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_system_events_ts'), ['ts'], unique=False)

    op.create_table('trade_journal',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('entry_type', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('strategy', sa.String(length=60), nullable=True),
    sa.Column('regime', sa.String(length=24), nullable=True),
    sa.Column('signal_score', sa.Float(), nullable=True),
    sa.Column('entry_time', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('exit_time', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('stop', sa.Float(), nullable=True),
    sa.Column('lots', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('slippage', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('mfe_r', sa.Float(), nullable=True),
    sa.Column('mae_r', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=12), nullable=False),
    sa.Column('ai_reasoning', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('signal_id', sa.String(length=40), nullable=True),
    sa.Column('position_id', sa.String(length=40), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trade_journal', schema=None) as batch_op:
        batch_op.create_index('ix_journal_symbol_time', ['symbol', 'entry_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_journal_entry_type'), ['entry_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_journal_position_id'), ['position_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_journal_regime'), ['regime'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_journal_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_journal_signal_id'), ['signal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trade_journal_strategy'), ['strategy'], unique=False)

    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('backtest_id', sa.String(length=40), nullable=False),
    sa.Column('trade_no', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=6), nullable=False),
    sa.Column('entry_time', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('exit_time', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=False),
    sa.Column('lots', sa.Float(), nullable=False),
    sa.Column('pnl', sa.Float(), nullable=False),
    sa.Column('pnl_r', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('exit_reason', sa.String(length=20), nullable=False),
    sa.Column('regime', sa.String(length=24), nullable=True),
    sa.Column('bars_held', sa.Integer(), nullable=False),
    sa.Column('mfe_r', sa.Float(), nullable=True),
    sa.Column('mae_r', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['backtest_id'], ['backtests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_trades_backtest_id'), ['backtest_id'], unique=False)

    op.create_table('paper_fills',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.String(length=40), nullable=False),
    sa.Column('position_id', sa.String(length=40), nullable=False),
    sa.Column('timestamp', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_fills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_fills_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_fills_position_id'), ['position_id'], unique=False)

    op.create_table('paper_orders',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.create_index('ix_order_account_status', ['account_id', 'status'], unique=False)

    op.create_table('paper_positions',
    sa.Column('id', sa.String(length=40), nullable=False),
    sa.Column('account_id', sa.String(length=40), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('opened_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('closed_at', app.core.database.UTCDateTime(timezone=True), nullable=True),
    sa.Column('strategy', sa.String(length=60), nullable=True),
    sa.Column('signal_id', sa.String(length=40), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_positions_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_pos_account_status', ['account_id', 'status'], unique=False)

    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.String(length=40), nullable=False),
    sa.Column('ts', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('margin_used', sa.Float(), nullable=False),
    sa.Column('unrealized_pnl', sa.Float(), nullable=False),
    sa.Column('open_positions', sa.Integer(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('is_demo_prices', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.create_index('ix_snapshot_account_ts', ['account_id', 'ts'], unique=False)

    op.create_table('signal_ai_analysis',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('signal_id', sa.String(length=40), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('prompt_name', sa.String(length=60), nullable=True),
    sa.Column('prompt_version', sa.String(length=16), nullable=True),
    sa.Column('prompt_date', sa.String(length=16), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('output', sa.JSON(), nullable=True),
    sa.Column('validation', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('created_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('signal_ai_analysis', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_ai_analysis_signal_id'), ['signal_id'], unique=False)

    op.create_table('signal_features',
    sa.Column('signal_id', sa.String(length=40), nullable=False),
    sa.Column('feature_version', sa.String(length=16), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('vector', sa.JSON(), nullable=True),
    sa.Column('structure', sa.JSON(), nullable=False),
    sa.Column('mtf', sa.JSON(), nullable=False),
    sa.Column('regime', sa.JSON(), nullable=False),
    sa.Column('data_quality', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_id')
    )
    op.create_table('signal_outcomes',
    sa.Column('signal_id', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('filled', sa.Boolean(), nullable=False),
    sa.Column('fill_time', sa.String(length=40), nullable=True),
    sa.Column('fill_price', sa.Float(), nullable=True),
    sa.Column('exit_time', sa.String(length=40), nullable=True),
    sa.Column('exit_reason', sa.String(length=30), nullable=True),
    sa.Column('r_multiple', sa.Float(), nullable=True),
    sa.Column('mfe_r', sa.Float(), nullable=True),
    sa.Column('mae_r', sa.Float(), nullable=True),
    sa.Column('tp_hits', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('updated_at', app.core.database.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('signal_id')
    )
    with op.batch_alter_table('signal_outcomes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_signal_outcomes_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signal_outcomes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_outcomes_status'))

    op.drop_table('signal_outcomes')
    op.drop_table('signal_features')
    with op.batch_alter_table('signal_ai_analysis', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signal_ai_analysis_signal_id'))

    op.drop_table('signal_ai_analysis')
    with op.batch_alter_table('portfolio_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_snapshot_account_ts')

    op.drop_table('portfolio_snapshots')
    with op.batch_alter_table('paper_positions', schema=None) as batch_op:
        batch_op.drop_index('ix_pos_account_status')
        batch_op.drop_index(batch_op.f('ix_paper_positions_symbol'))

    op.drop_table('paper_positions')
    with op.batch_alter_table('paper_orders', schema=None) as batch_op:
        batch_op.drop_index('ix_order_account_status')

    op.drop_table('paper_orders')
    with op.batch_alter_table('paper_fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_fills_position_id'))
        batch_op.drop_index(batch_op.f('ix_paper_fills_account_id'))

    op.drop_table('paper_fills')
    with op.batch_alter_table('backtest_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_trades_backtest_id'))

    op.drop_table('backtest_trades')
    with op.batch_alter_table('trade_journal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trade_journal_strategy'))
        batch_op.drop_index(batch_op.f('ix_trade_journal_signal_id'))
        batch_op.drop_index(batch_op.f('ix_trade_journal_result'))
        batch_op.drop_index(batch_op.f('ix_trade_journal_regime'))
        batch_op.drop_index(batch_op.f('ix_trade_journal_position_id'))
        batch_op.drop_index(batch_op.f('ix_trade_journal_entry_type'))
        batch_op.drop_index('ix_journal_symbol_time')

    op.drop_table('trade_journal')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_events_ts'))
        batch_op.drop_index(batch_op.f('ix_system_events_signal_id'))
        batch_op.drop_index(batch_op.f('ix_system_events_event_type'))

    op.drop_table('system_events')
    with op.batch_alter_table('strategy_regime_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_regime_stats_strategy'))

    op.drop_table('strategy_regime_stats')
    op.drop_table('strategies')
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_signals_timeframe'))
        batch_op.drop_index(batch_op.f('ix_signals_score'))
        batch_op.drop_index(batch_op.f('ix_signals_is_demo'))
        batch_op.drop_index(batch_op.f('ix_signals_direction'))
        batch_op.drop_index('ix_signal_symbol_time')
        batch_op.drop_index('ix_signal_status')
        batch_op.drop_index('ix_signal_dedupe')

    op.drop_table('signals')
    op.drop_table('paper_accounts')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_ts'))

    op.drop_table('notifications')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_published_at'))

    op.drop_table('news')
    op.drop_table('model_versions')
    with op.batch_alter_table('market_regimes', schema=None) as batch_op:
        batch_op.drop_index('ix_regime_lookup')
        batch_op.drop_index(batch_op.f('ix_market_regimes_regime'))

    op.drop_table('market_regimes')
    with op.batch_alter_table('market_features', schema=None) as batch_op:
        batch_op.drop_index('ix_feature_lookup')

    op.drop_table('market_features')
    with op.batch_alter_table('market_candles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_candles_is_demo'))
        batch_op.drop_index('ix_candle_lookup')

    op.drop_table('market_candles')
    with op.batch_alter_table('market_assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_market_assets_asset_class'))

    op.drop_table('market_assets')
    with op.batch_alter_table('historical_setups', schema=None) as batch_op:
        batch_op.drop_index('ix_setup_lookup')
        batch_op.drop_index(batch_op.f('ix_historical_setups_ts'))
        batch_op.drop_index(batch_op.f('ix_historical_setups_outcome_status'))

    op.drop_table('historical_setups')
    with op.batch_alter_table('economic_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_economic_events_scheduled_at'))
        batch_op.drop_index(batch_op.f('ix_economic_events_impact'))
        batch_op.drop_index(batch_op.f('ix_economic_events_currency'))

    op.drop_table('economic_events')
    with op.batch_alter_table('briefings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_briefings_session'))

    op.drop_table('briefings')
    with op.batch_alter_table('backtests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtests_symbol'))
        batch_op.drop_index(batch_op.f('ix_backtests_strategy'))

    op.drop_table('backtests')
    op.drop_table('app_settings')
    op.drop_table('alerts')
    with op.batch_alter_table('ai_calls', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_calls_provider'))
        batch_op.drop_index(batch_op.f('ix_ai_calls_created_at'))

    op.drop_table('ai_calls')
    # ### end Alembic commands ###
